"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, Card } from "@/components/ui";
import { ArrowLeft } from "@/components/icons";
import { getWeek, generateSundayReport, pressureGap, focusSleepInsight, type ReportLine } from "@/lib/mental";
import { useBaselineStore } from "@/lib/store";

/**
 * The Sunday Report (spec I6/G1) — the retention engine. Every line here is
 * generated by the deterministic report generator from a real logged value; if a
 * number can't be sourced, the sentence doesn't render.
 */
export default function ReportPage() {
  const router = useRouter();
  const {
    subscription, alterEgo, currentWeekIndex, blockCompletions,
    pressureFTs, tensionAudits, intentions, focusRatings, quietHands,
  } = useBaselineStore();
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => setHydrated(true), []);
  useEffect(() => {
    if (hydrated && !subscription.active) router.replace("/paywall");
  }, [hydrated, subscription.active, router]);

  const week = getWeek(currentWeekIndex);

  const report = useMemo(() => {
    if (!week) return null;
    const done = week.days.filter((d) => blockCompletions[`${week.index}:${d.day}`]);
    const missedTitles = week.days
      .filter((d) => d.minutes != null && !blockCompletions[`${week.index}:${d.day}`])
      .map((d) => d.title);

    const gapOf = (i: number) => (pressureFTs[i] ? pressureGap(pressureFTs[i]!).gap ?? undefined : undefined);
    const shoulder = (i: number) => tensionAudits[i]?.shoulders;
    const n = pressureFTs.length;
    const m = tensionAudits.length;
    const insight = focusSleepInsight(focusRatings) ?? undefined;

    return generateSundayReport({
      weekName: week.name,
      nextTeaser: week.nextTeaser,
      alterEgo: alterEgo?.name,
      blocksCompleted: done.length,
      blocksTotal: 7,
      missedTitles,
      eightyFive: quietHands ?? undefined,
      tensionThis: shoulder(m - 1),
      tensionPrior: shoulder(m - 2),
      pressureGapThis: gapOf(n - 1),
      pressureGapPrior: gapOf(n - 2),
      intentionGrade: intentions.find((i) => i.weekIndex === week.index)?.grade,
      focusInsight: insight,
    });
  }, [week, blockCompletions, pressureFTs, tensionAudits, intentions, focusRatings, quietHands, alterEgo]);

  if (!hydrated || !week || !report) return <div className="pt-24 text-center text-white/40">Loading The Report…</div>;

  const win = report.lines.find((l) => l.kind === "win");

  return (
    <div className="pb-28">
      <header className="flex items-center gap-3 pt-2">
        <button onClick={() => router.push("/week")} aria-label="Back" className="pressable -ml-1 rounded-lg p-1 text-white/60 hover:text-white">
          <ArrowLeft className="h-6 w-6" />
        </button>
        <div>
          <p className="eyebrow">The Report</p>
          <h1 className="font-display text-xl uppercase tracking-tight">{report.weekName}</h1>
        </div>
      </header>

      {/* The week-3 reveal moment: the headline win, big. */}
      {win && (
        <section className="mt-6 animate-scale-in">
          <div className="surface relative overflow-hidden p-6 text-center">
            <div className="pointer-events-none absolute inset-x-0 -top-6 mx-auto h-40 w-40 animate-glow-pulse rounded-full bg-amber-500/25 blur-3xl" />
            <p className="eyebrow relative">This week</p>
            <p className="relative mt-2 text-[17px] font-semibold leading-relaxed text-white">{win.text}</p>
          </div>
        </section>
      )}

      <section className="mt-4 space-y-2.5">
        {report.lines.filter((l) => l !== win).map((line, i) => (
          <ReportLineCard key={i} line={line} />
        ))}
      </section>

      <section className="mt-6">
        <Card className="text-center">
          <p className="eyebrow">Next week</p>
          <p className="mt-2 font-display text-2xl uppercase tracking-tight text-amber-500">{report.nextTeaser}</p>
          <p className="mt-2 text-sm text-white/50">See you Monday.</p>
        </Card>
      </section>

      <div className="mt-5 flex gap-2">
        <Button variant="ghost" onClick={() => shareReport(report.weekName, win?.text)}>Share this</Button>
        <Button onClick={() => router.push("/week")}>Back to the week</Button>
      </div>
      <p className="mt-4 text-center text-[11px] text-white/30">Every line above comes from a value you logged. Nothing here is invented.</p>
    </div>
  );
}

function ReportLineCard({ line }: { line: ReportLine }) {
  const tone = line.kind === "win" ? "text-readiness-green" : line.kind === "honest" ? "text-readiness-yellow" : "text-white/45";
  const mark = line.kind === "win" ? "▲" : line.kind === "honest" ? "•" : "›";
  return (
    <div className="surface p-4">
      <p className="text-[15px] leading-relaxed text-white/85"><span className={`mr-2 ${tone}`}>{mark}</span>{line.text}</p>
    </div>
  );
}

function shareReport(weekName: string, win?: string) {
  const text = `THE WEEK — ${weekName}. ${win ?? ""}`.trim();
  if (typeof navigator !== "undefined" && navigator.share) {
    void navigator.share({ text }).catch(() => {});
  } else if (typeof navigator !== "undefined") {
    void navigator.clipboard?.writeText(text);
  }
}
