/**
 * Curated shoe catalog (spec 5.3). Real, existing models with EDITORIAL 1–10
 * ratings (opinion — not fabricated hard specs) and price BANDS (not precise
 * current prices). `lastUpdated` is shown in the UI, which also tells users to
 * verify current retail. Swap this provider for a live/admin source later.
 */

import type { Shoe, ShoeCatalog, ShoeCatalogProvider } from "./types";

const SHOES: Shoe[] = [
  { id: "nike-gt-cut", name: "Nike G.T. Cut", brand: "Nike", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 10, traction: 9, outdoorDurability: 5, support: 7, fit: "true", bestFor: ["shifty_guard", "movement_shooter"], worstFor: ["Heavier players wanting max cushion"], priceBand: "$$$", approxMSRP: "$180–190", similarTo: ["kobe-protro", "curry-flow"], cushioningSystem: "Zoom Air" },
  { id: "nike-lebron", name: "Nike LeBron", brand: "Nike", releaseYear: 2024, cut: "mid", weightClass: "heavy", impactProtection: 10, courtFeel: 5, traction: 8, outdoorDurability: 6, support: 9, fit: "wide", bestFor: ["explosive_slasher", "post_big"], worstFor: ["Guards wanting court feel"], priceBand: "$$$", approxMSRP: "$180–200", similarTo: ["ua-embiid", "jordan-zion"], cushioningSystem: "Max Air + Zoom" },
  { id: "kobe-protro", name: "Nike Kobe Protro", brand: "Nike", line: "Kobe", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 9, traction: 9, outdoorDurability: 5, support: 8, fit: "true", bestFor: ["shifty_guard", "wing_defender", "all_around"], worstFor: ["Players needing plush heel"], priceBand: "$$$", approxMSRP: "$180", similarTo: ["nike-gt-cut", "puma-mb"], cushioningSystem: "Zoom Air" },
  { id: "nike-giannis-freak", name: "Nike Giannis Freak", brand: "Nike", releaseYear: 2024, cut: "mid", weightClass: "standard", impactProtection: 8, courtFeel: 6, traction: 8, outdoorDurability: 7, support: 8, fit: "true", bestFor: ["explosive_slasher", "wing_defender"], worstFor: ["Pure shooters wanting low profile"], priceBand: "$$", approxMSRP: "$110–130", similarTo: ["adidas-dame", "nike-lebron"], cushioningSystem: "Zoom Air" },
  { id: "jordan-luka", name: "Jordan Luka", brand: "Jordan", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 7, courtFeel: 8, traction: 8, outdoorDurability: 6, support: 7, fit: "true", bestFor: ["shifty_guard", "all_around"], worstFor: ["Explosive vertical athletes wanting max Air"], priceBand: "$$", approxMSRP: "$120–140", similarTo: ["jordan-tatum", "nike-gt-cut"], cushioningSystem: "Formula 23 foam" },
  { id: "jordan-tatum", name: "Jordan Tatum", brand: "Jordan", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 9, traction: 8, outdoorDurability: 6, support: 7, fit: "true", bestFor: ["wing_defender", "shifty_guard", "all_around"], worstFor: ["Bigs wanting heel stability"], priceBand: "$$", approxMSRP: "$110–130", similarTo: ["jordan-luka", "kobe-protro"] },
  { id: "jordan-zion", name: "Jordan Zion", brand: "Jordan", releaseYear: 2024, cut: "mid", weightClass: "heavy", impactProtection: 9, courtFeel: 5, traction: 8, outdoorDurability: 7, support: 9, fit: "wide", bestFor: ["explosive_slasher", "post_big"], worstFor: ["Narrow feet", "Guards wanting court feel"], priceBand: "$$", approxMSRP: "$140", similarTo: ["nike-lebron", "ua-embiid"] },
  { id: "adidas-harden", name: "adidas Harden", brand: "adidas", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 8, courtFeel: 7, traction: 8, outdoorDurability: 6, support: 7, fit: "true", bestFor: ["shifty_guard", "movement_shooter"], worstFor: ["Players wanting a locked-down high cut"], priceBand: "$$", approxMSRP: "$130–160", similarTo: ["adidas-dame", "curry-flow"], cushioningSystem: "Boost" },
  { id: "adidas-dame", name: "adidas Dame", brand: "adidas", releaseYear: 2024, cut: "mid", weightClass: "standard", impactProtection: 7, courtFeel: 8, traction: 8, outdoorDurability: 8, support: 7, fit: "true", bestFor: ["all_around", "shifty_guard"], worstFor: ["Players wanting premium plush cushion"], priceBand: "$", approxMSRP: "$70–110", similarTo: ["adidas-don", "adidas-harden"], cushioningSystem: "Bounce" },
  { id: "adidas-don", name: "adidas D.O.N. (Mitchell)", brand: "adidas", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 9, traction: 8, outdoorDurability: 7, support: 7, fit: "true", bestFor: ["shifty_guard", "explosive_slasher"], worstFor: ["Bigs wanting max support"], priceBand: "$", approxMSRP: "$100", similarTo: ["adidas-dame", "kobe-protro"], cushioningSystem: "Bounce" },
  { id: "adidas-trae", name: "adidas Trae Young", brand: "adidas", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 7, courtFeel: 8, traction: 7, outdoorDurability: 5, support: 6, fit: "narrow", bestFor: ["shifty_guard", "movement_shooter"], worstFor: ["Wide feet", "Physical wings/bigs"], priceBand: "$$", approxMSRP: "$120", similarTo: ["adidas-harden", "jordan-luka"] },
  { id: "curry-flow", name: "Under Armour Curry Flow", brand: "Under Armour", line: "Curry", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 9, traction: 10, outdoorDurability: 4, support: 7, fit: "true", bestFor: ["movement_shooter", "shifty_guard"], worstFor: ["Outdoor players (soft Flow rubber)"], priceBand: "$$", approxMSRP: "$140–160", similarTo: ["nike-gt-cut", "kobe-protro"], cushioningSystem: "Flow" },
  { id: "ua-embiid", name: "Under Armour Embiid", brand: "Under Armour", releaseYear: 2024, cut: "mid", weightClass: "heavy", impactProtection: 9, courtFeel: 5, traction: 8, outdoorDurability: 7, support: 9, fit: "wide", bestFor: ["post_big", "explosive_slasher"], worstFor: ["Guards wanting low profile"], priceBand: "$$", approxMSRP: "$160", similarTo: ["nike-lebron", "jordan-zion"] },
  { id: "puma-mb", name: "Puma MB (LaMelo)", brand: "Puma", line: "MB", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 7, courtFeel: 8, traction: 8, outdoorDurability: 6, support: 7, fit: "true", bestFor: ["shifty_guard", "all_around"], worstFor: ["Post players wanting heel lockdown"], priceBand: "$$", approxMSRP: "$125", similarTo: ["puma-court-rider", "jordan-luka"], cushioningSystem: "Nitro" },
  { id: "puma-court-rider", name: "Puma Court Rider", brand: "Puma", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 6, courtFeel: 8, traction: 7, outdoorDurability: 7, support: 6, fit: "true", bestFor: ["all_around", "shifty_guard"], worstFor: ["Players wanting premium cushion"], priceBand: "$", approxMSRP: "$70–90", similarTo: ["adidas-dame", "puma-mb"] },
  { id: "puma-clyde-allpro", name: "Puma Clyde All-Pro", brand: "Puma", releaseYear: 2023, cut: "low", weightClass: "light", impactProtection: 6, courtFeel: 9, traction: 8, outdoorDurability: 6, support: 7, fit: "true", bestFor: ["wing_defender", "shifty_guard", "movement_shooter"], worstFor: ["Heavier players wanting max impact protection"], priceBand: "$$", approxMSRP: "$120", similarTo: ["kobe-protro", "nb-twoxy"] },
  { id: "nb-twoxy", name: "New Balance TWO WXY", brand: "New Balance", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 8, courtFeel: 7, traction: 8, outdoorDurability: 7, support: 8, fit: "true", bestFor: ["wing_defender", "all_around"], worstFor: ["Shooters wanting the lowest profile"], priceBand: "$$", approxMSRP: "$135", similarTo: ["nb-kawhi", "puma-mb"], cushioningSystem: "FuelCell" },
  { id: "nb-kawhi", name: "New Balance Kawhi", brand: "New Balance", releaseYear: 2023, cut: "mid", weightClass: "standard", impactProtection: 8, courtFeel: 6, traction: 8, outdoorDurability: 7, support: 9, fit: "wide", bestFor: ["wing_defender", "post_big"], worstFor: ["Narrow feet", "Pure speed guards"], priceBand: "$$", approxMSRP: "$140", similarTo: ["nb-twoxy", "ua-embiid"], cushioningSystem: "FuelCell" },
  { id: "anta-kt", name: "Anta KT (Klay Thompson)", brand: "Anta", line: "KT", releaseYear: 2024, cut: "mid", weightClass: "standard", impactProtection: 8, courtFeel: 7, traction: 8, outdoorDurability: 8, support: 8, fit: "true", bestFor: ["movement_shooter", "all_around"], worstFor: ["Players wanting a premium brand feel"], priceBand: "$", approxMSRP: "$80–110", similarTo: ["lining-yushuai", "nb-twoxy"], cushioningSystem: "A-Flashfoam" },
  { id: "lining-yushuai", name: "Li-Ning Yushuai", brand: "Li-Ning", releaseYear: 2024, cut: "low", weightClass: "light", impactProtection: 7, courtFeel: 9, traction: 8, outdoorDurability: 7, support: 7, fit: "narrow", bestFor: ["shifty_guard", "movement_shooter"], worstFor: ["Wide feet"], priceBand: "$", approxMSRP: "$90–120", similarTo: ["anta-kt", "wow-allcity"], cushioningSystem: "Boom / Cloud" },
  { id: "lining-cjm", name: "Li-Ning CJ McCollum", brand: "Li-Ning", releaseYear: 2023, cut: "low", weightClass: "standard", impactProtection: 7, courtFeel: 8, traction: 8, outdoorDurability: 7, support: 7, fit: "true", bestFor: ["shifty_guard", "all_around"], worstFor: ["Bigs wanting heel stability"], priceBand: "$", approxMSRP: "$100", similarTo: ["lining-yushuai", "puma-mb"] },
  { id: "wow-allcity", name: "Way of Wade All City", brand: "Way of Wade", releaseYear: 2024, cut: "low", weightClass: "standard", impactProtection: 8, courtFeel: 8, traction: 8, outdoorDurability: 7, support: 8, fit: "true", bestFor: ["all_around", "wing_defender"], worstFor: ["Players wanting the absolute lightest build"], priceBand: "$$", approxMSRP: "$120–150", similarTo: ["wow-10", "anta-kt"], cushioningSystem: "Boom" },
  { id: "wow-10", name: "Way of Wade 10", brand: "Way of Wade", releaseYear: 2023, cut: "mid", weightClass: "standard", impactProtection: 9, courtFeel: 7, traction: 8, outdoorDurability: 6, support: 8, fit: "true", bestFor: ["explosive_slasher", "all_around"], worstFor: ["Outdoor-primary players"], priceBand: "$$$", approxMSRP: "$200", similarTo: ["wow-allcity", "nike-lebron"], cushioningSystem: "Boom" },
  { id: "361-big3", name: "361° BIG3", brand: "361°", releaseYear: 2023, cut: "mid", weightClass: "standard", impactProtection: 8, courtFeel: 7, traction: 8, outdoorDurability: 8, support: 8, fit: "true", bestFor: ["all_around", "wing_defender"], worstFor: ["Premium-brand seekers"], priceBand: "$", approxMSRP: "$90–120", similarTo: ["anta-kt", "wow-allcity"], cushioningSystem: "QU!KFOAM" },
  { id: "reebok-question", name: "Reebok Question", brand: "Reebok", releaseYear: 2023, cut: "mid", weightClass: "standard", impactProtection: 6, courtFeel: 6, traction: 7, outdoorDurability: 7, support: 7, fit: "true", bestFor: ["all_around"], worstFor: ["Performance-first players (this leans lifestyle)"], priceBand: "$$", approxMSRP: "$140", similarTo: ["converse-allstar-pro"], cushioningSystem: "Hexalite" },
  { id: "converse-allstar-pro", name: "Converse All Star Pro BB", brand: "Converse", releaseYear: 2023, cut: "mid", weightClass: "standard", impactProtection: 7, courtFeel: 7, traction: 8, outdoorDurability: 7, support: 7, fit: "true", bestFor: ["all_around", "wing_defender"], worstFor: ["Explosive bigs wanting max cushion"], priceBand: "$$", approxMSRP: "$120", similarTo: ["reebok-question", "puma-court-rider"], cushioningSystem: "CX foam" },
];

const CATALOG: ShoeCatalog = {
  lastUpdated: "2026-07-01",
  shoes: SHOES,
};

export class CuratedShoeCatalogProvider implements ShoeCatalogProvider {
  readonly id = "curated";
  getCatalog(): ShoeCatalog {
    return CATALOG;
  }
}

export const SHOE_CATALOG = CATALOG;
