/**
 * Seed drill library (spec Part 3.3).
 *
 * This is a REPRESENTATIVE library (~55 drills) covering every category and
 * tier, each with cues, equipment, DNA targets, CNS load, injury regions, and a
 * progression + regression. The spec's target is ≥150; the schema and generator
 * fully support that — filling the library to 150 is ongoing content work, not
 * an engine change. `d()` fills sensible defaults so each entry stays readable.
 */

import type { Drill, DrillCategory, Tier, Equipment, CNSLoad, BodyRegion } from "./types";
import type { DimensionKey } from "../dna/dimensions";

interface DrillSeed {
  id: string;
  name: string;
  category: DrillCategory;
  description: string;
  cues: string[];
  equipment?: Equipment[];
  tier?: Tier;
  develops: DimensionKey[];
  cnsLoad?: CNSLoad;
  regions?: BodyRegion[];
  dose: string;
  defaultSets?: number;
  progression: string;
  regression: string;
}

function d(s: DrillSeed): Drill {
  return {
    equipment: ["none"],
    tier: "intermediate",
    cnsLoad: "low",
    regions: ["none"],
    defaultSets: 3,
    ...s,
  };
}

export const DRILLS: Drill[] = [
  // ================= GYM: lower strength =================
  d({ id: "trap-bar-deadlift", name: "Trap-Bar Deadlift", category: "lower_strength", description: "Bilateral hinge for lower-body strength with a spine-friendly bar path.", cues: ["Push the floor away", "Ribs down, brace"], equipment: ["trap_bar"], tier: "intermediate", develops: ["strength_mass", "vertical_explosiveness"], cnsLoad: "high", regions: ["lower_back", "hip"], dose: "4 × 5", defaultSets: 4, progression: "Add load, then move to speed pulls", regression: "Kettlebell deadlift" }),
  d({ id: "rear-foot-split-squat", name: "Rear-Foot Elevated Split Squat", category: "lower_strength", description: "Unilateral squat pattern that builds single-leg strength and knee resilience.", cues: ["Vertical shin stacked", "Down through mid-foot"], equipment: ["dumbbells", "bench"], tier: "intermediate", develops: ["strength_mass", "lateral_quickness"], cnsLoad: "moderate", regions: ["knee", "hip"], dose: "3 × 8 / side", progression: "Add load or deficit", regression: "Bodyweight split squat" }),
  d({ id: "nordic-curl", name: "Nordic Hamstring Curl", category: "lower_strength", description: "Eccentric hamstring strength for sprint speed and hamstring-injury resilience.", cues: ["Lower as slow as possible", "Hips locked out"], equipment: ["partner"], tier: "advanced", develops: ["strength_mass", "first_step_burst"], cnsLoad: "moderate", regions: ["knee"], dose: "3 × 5", progression: "Slower eccentric, then assisted concentric", regression: "Band-assisted Nordic" }),
  d({ id: "goblet-squat", name: "Goblet Squat", category: "lower_strength", description: "Beginner-friendly squat teaching depth and bracing.", cues: ["Elbows inside knees", "Tall chest"], equipment: ["dumbbells"], tier: "beginner", develops: ["strength_mass"], cnsLoad: "moderate", regions: ["knee", "hip"], dose: "3 × 10", progression: "Front squat", regression: "Box squat to a target" }),
  d({ id: "rdl", name: "Romanian Deadlift", category: "lower_strength", description: "Hip-hinge for posterior-chain strength and hamstring length.", cues: ["Hinge, soft knees", "Bar close to legs"], equipment: ["barbell"], tier: "intermediate", develops: ["strength_mass"], cnsLoad: "moderate", regions: ["lower_back", "hip"], dose: "3 × 8", progression: "Single-leg RDL", regression: "Dumbbell RDL" }),

  // ================= GYM: upper push/pull =================
  d({ id: "db-bench", name: "Dumbbell Bench Press", category: "upper_push_pull", description: "Horizontal press for upper-body strength with shoulder-friendly range.", cues: ["Shoulder blades down and back", "Control the descent"], equipment: ["dumbbells", "bench"], tier: "beginner", develops: ["strength_mass"], cnsLoad: "moderate", regions: ["shoulder"], dose: "4 × 8", defaultSets: 4, progression: "Barbell bench", regression: "Push-up" }),
  d({ id: "chin-up", name: "Chin-Up", category: "upper_push_pull", description: "Vertical pull for back and grip strength.", cues: ["Chest to bar", "Full hang at bottom"], equipment: ["rack"], tier: "intermediate", develops: ["strength_mass"], cnsLoad: "moderate", regions: ["shoulder"], dose: "4 × 6", defaultSets: 4, progression: "Weighted chin-up", regression: "Band-assisted chin-up" }),
  d({ id: "half-kneeling-press", name: "Half-Kneeling Landmine Press", category: "upper_push_pull", description: "Shoulder-health-biased press for shooters — pressing without impingement risk.", cues: ["Ribs down", "Press to the ceiling line"], equipment: ["barbell"], tier: "beginner", develops: ["strength_mass", "catch_and_shoot"], cnsLoad: "low", regions: ["shoulder"], dose: "3 × 10 / side", progression: "Tall-kneeling then standing", regression: "Band press" }),
  d({ id: "face-pull", name: "Band Face-Pull", category: "upper_push_pull", description: "Rear-delt and rotator-cuff health for shooters' shoulders.", cues: ["Pull to the eyes", "Thumbs back"], equipment: ["bands"], tier: "beginner", develops: ["catch_and_shoot"], cnsLoad: "low", regions: ["shoulder"], dose: "3 × 15", progression: "Add reps / slow tempo", regression: "Lighter band" }),

  // ================= GYM: power / plyo =================
  d({ id: "pogo-hops", name: "Pogo Hops (Extensive Plyo)", category: "power_plyo", description: "Low-intensity ankle stiffness and landing mechanics — the entry to plyos.", cues: ["Stiff ankles", "Quiet landings"], equipment: ["none"], tier: "beginner", develops: ["vertical_explosiveness", "first_step_burst"], cnsLoad: "moderate", regions: ["ankle"], dose: "4 × 20", defaultSets: 4, progression: "Single-leg pogos", regression: "Reduce contacts" }),
  d({ id: "box-jump", name: "Box Jump (Intensive Plyo)", category: "power_plyo", description: "Concentric jump power with a soft landing — teaches force production.", cues: ["Explode up", "Land soft, absorb"], equipment: ["box"], tier: "intermediate", develops: ["vertical_explosiveness"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "5 × 3", defaultSets: 5, progression: "Higher box / single response", regression: "Lower box, step down" }),
  d({ id: "depth-jump", name: "Depth Jump (Reactive Plyo)", category: "power_plyo", description: "Reactive strength — fast ground contact off a drop. Advanced: mechanics first.", cues: ["Minimize ground time", "Land and pop"], equipment: ["box"], tier: "advanced", develops: ["vertical_explosiveness", "first_step_burst"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "5 × 3", defaultSets: 5, progression: "Higher drop, single-leg", regression: "Box jump" }),
  d({ id: "med-ball-slam", name: "Med-Ball Overhead Slam", category: "power_plyo", description: "Full-body power expression, low landing demand.", cues: ["Reach tall", "Slam through the floor"], equipment: ["med_ball"], tier: "beginner", develops: ["vertical_explosiveness", "strength_mass"], cnsLoad: "moderate", regions: ["none"], dose: "4 × 6", defaultSets: 4, progression: "Heavier ball, rotational slam", regression: "Lighter ball" }),
  d({ id: "broad-jump", name: "Standing Broad Jump", category: "power_plyo", description: "Horizontal power for first-step and acceleration.", cues: ["Big arm swing", "Stick the landing"], equipment: ["none"], tier: "intermediate", develops: ["first_step_burst", "vertical_explosiveness"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "5 × 3", defaultSets: 5, progression: "Repeated broad jumps", regression: "Reduce distance, focus landing" }),

  // ================= GYM: speed / change of direction =================
  d({ id: "wall-drive", name: "Wall Drive Acceleration", category: "speed_cod", description: "Acceleration mechanics — shin angles and punch of the knee.", cues: ["Tall spine", "Punch knee, strike down"], equipment: ["wall"], tier: "beginner", develops: ["first_step_burst"], cnsLoad: "moderate", regions: ["none"], dose: "4 × 5 / side", progression: "Falling-start sprints", regression: "Marching drive" }),
  d({ id: "45-cut", name: "45° Cut Deceleration", category: "speed_cod", description: "Change-of-direction mechanics — decelerate and redirect at 45°.", cues: ["Sink hips to brake", "Push off outside foot"], equipment: ["cones"], tier: "intermediate", develops: ["lateral_quickness", "first_step_burst"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "6 × 2 / side", defaultSets: 6, progression: "90° cut, reactive on call", regression: "Slower, submaximal cuts" }),
  d({ id: "lateral-bound", name: "Lateral Bound & Stick", category: "speed_cod", description: "Single-leg lateral power and landing control for slides and cuts.", cues: ["Push to the horizon", "Stick 2 seconds"], equipment: ["none"], tier: "intermediate", develops: ["lateral_quickness", "vertical_explosiveness"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "4 × 4 / side", defaultSets: 4, progression: "Continuous bounds", regression: "Smaller bound, focus stick" }),
  d({ id: "shuttle-5-10-5", name: "5-10-5 Pro Agility", category: "speed_cod", description: "Classic change-of-direction test and trainer.", cues: ["Low on the turn", "Touch and explode"], equipment: ["cones"], tier: "advanced", develops: ["lateral_quickness", "first_step_burst", "endurance"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "6 reps", defaultSets: 0, progression: "Reactive start", regression: "Reduce reps, submaximal" }),

  // ================= GYM: core =================
  d({ id: "pallof-press", name: "Pallof Press (Anti-Rotation)", category: "core", description: "Resists rotation — transfers force through the trunk on drives and passes.", cues: ["Ribs down", "Resist the twist"], equipment: ["bands"], tier: "beginner", develops: ["handle_under_pressure", "strength_mass"], cnsLoad: "low", regions: ["lower_back"], dose: "3 × 10 / side", progression: "Split-stance / tall-kneeling", regression: "Lighter band, closer to anchor" }),
  d({ id: "hollow-hold", name: "Hollow-Body Hold (Anti-Extension)", category: "core", description: "Anti-extension bracing for a stiff, efficient trunk.", cues: ["Low back glued down", "Long body"], equipment: ["none"], tier: "beginner", develops: ["strength_mass"], cnsLoad: "low", regions: ["lower_back"], dose: "3 × 30s", defaultSets: 3, progression: "Hollow rocks", regression: "Tuck hold" }),
  d({ id: "suitcase-carry", name: "Suitcase Carry", category: "core", description: "Loaded carry for anti-lateral-flexion and grip.", cues: ["Stand tall, don't lean", "Slow controlled steps"], equipment: ["dumbbells"], tier: "beginner", develops: ["strength_mass"], cnsLoad: "low", regions: ["lower_back"], dose: "3 × 40 yd", defaultSets: 3, progression: "Heavier load", regression: "Lighter, shorter carry" }),

  // ================= GYM: prehab =================
  d({ id: "calf-raise-rom", name: "Full-ROM Calf Raise", category: "prehab", description: "Ankle and calf strength through full range — landing and jump durability.", cues: ["Deep stretch at bottom", "Pause at the top"], equipment: ["none"], tier: "beginner", develops: ["vertical_explosiveness"], cnsLoad: "low", regions: ["ankle"], dose: "3 × 15", progression: "Single-leg, loaded", regression: "Double-leg, bodyweight" }),
  d({ id: "tib-raise", name: "Tibialis Raise", category: "prehab", description: "Front-of-shin strength for deceleration and shin-splint resilience.", cues: ["Toes to shin", "Control down"], equipment: ["wall"], tier: "beginner", develops: ["lateral_quickness"], cnsLoad: "low", regions: ["ankle"], dose: "3 × 20", progression: "Add load", regression: "Reduce range" }),
  d({ id: "spanish-squat", name: "Spanish Squat (Tendon Isometric)", category: "prehab", description: "Knee-tendon isometric for patellar-tendon health (VMO bias).", cues: ["Shins vertical", "Squeeze quads hard"], equipment: ["bands"], tier: "beginner", develops: ["strength_mass"], cnsLoad: "low", regions: ["knee"], dose: "5 × 30s", defaultSets: 5, progression: "Longer holds / load", regression: "Shorter holds" }),
  d({ id: "copenhagen", name: "Copenhagen Plank (Adductor)", category: "prehab", description: "Adductor/groin strength for cutting and slide durability.", cues: ["Straight line", "Top leg drives down"], equipment: ["bench"], tier: "intermediate", develops: ["lateral_quickness"], cnsLoad: "low", regions: ["hip"], dose: "3 × 20s / side", progression: "Long-lever Copenhagen", regression: "Short-lever, knee support" }),
  d({ id: "landing-mechanics", name: "Drop-Landing Mechanics", category: "prehab", description: "Deceleration and landing pattern — knees track over toes, absorb quietly.", cues: ["Land soft", "Knees over toes, not in"], equipment: ["box"], tier: "beginner", develops: ["vertical_explosiveness", "lateral_quickness"], cnsLoad: "low", regions: ["knee", "ankle"], dose: "4 × 5", defaultSets: 4, progression: "Single-leg landings", regression: "Lower height" }),

  // ================= GYM: conditioning =================
  d({ id: "repeat-sprint", name: "Repeat-Sprint Ability", category: "conditioning", description: "Basketball's energy system — short max sprints with incomplete rest.", cues: ["Max effort each rep", "Hold your times"], equipment: ["court"], tier: "intermediate", develops: ["endurance", "first_step_burst"], cnsLoad: "high", regions: ["none"], dose: "10 × 15s / 45s rest", defaultSets: 0, progression: "More reps / shorter rest", regression: "Fewer reps, longer rest" }),
  d({ id: "tempo-runs", name: "Tempo Runs", category: "conditioning", description: "Aerobic base at ~70% — builds recovery capacity between efforts.", cues: ["Relaxed and smooth", "Nasal breathing"], equipment: ["court"], tier: "beginner", develops: ["endurance"], cnsLoad: "low", regions: ["none"], dose: "10 × 20s / walk back", defaultSets: 0, progression: "More reps", regression: "Fewer reps" }),
  d({ id: "suicide-conditioning", name: "Line Drills (Suicides)", category: "conditioning", description: "Court-specific repeat efforts with change of direction.", cues: ["Touch every line", "Low turns"], equipment: ["court"], tier: "intermediate", develops: ["endurance", "lateral_quickness"], cnsLoad: "high", regions: ["ankle"], dose: "6 reps / 60s rest", defaultSets: 0, progression: "More reps, tighter rest", regression: "Fewer reps" }),

  // ================= COURT: shooting =================
  d({ id: "form-shooting", name: "Form Shooting (Close)", category: "shooting", description: "Groove mechanics from 3-5 feet — one hand then two, straight line.", cues: ["Elbow under ball", "Hold the follow-through"], equipment: ["ball", "hoop"], tier: "beginner", develops: ["catch_and_shoot"], cnsLoad: "low", regions: ["none"], dose: "50 makes", defaultSets: 0, progression: "Step back to free-throw line", regression: "Closer, slower reps" }),
  d({ id: "spot-catch-shoot", name: "Catch-and-Shoot — 5 Spots", category: "shooting", description: "Set feet, quick release from five perimeter spots.", cues: ["Feet ready before the catch", "Same release every time"], equipment: ["ball", "hoop"], tier: "intermediate", develops: ["catch_and_shoot", "movement_shooting"], cnsLoad: "low", regions: ["none"], dose: "10 makes / spot", defaultSets: 0, progression: "On the move / off a pass", regression: "Fewer spots, closer range" }),
  d({ id: "relocation-shooting", name: "Relocation Catch-and-Shoot", category: "shooting", description: "Shoot, relocate to a new spot, repeat — off-ball movement + shooting.", cues: ["Sprint to space", "Feet set on the catch"], equipment: ["ball", "hoop", "partner"], tier: "intermediate", develops: ["movement_shooting", "off_ball_iq", "off_screen_navigation"], cnsLoad: "moderate", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Off screens", regression: "Walk to spots" }),
  d({ id: "pullup-series", name: "Pull-Up Jumper Series", category: "shooting", description: "Off-the-dribble pull-ups — one and two dribbles, both directions.", cues: ["Gather into balance", "Rise straight up"], equipment: ["ball", "hoop"], tier: "advanced", develops: ["off_dribble_shooting", "handle_under_pressure"], cnsLoad: "moderate", regions: ["none"], dose: "10 makes / direction", defaultSets: 0, progression: "Step-back and side-step", regression: "One-dribble only, closer" }),
  d({ id: "off-screen-shooting", name: "Off-Screen Shooting", category: "shooting", description: "Come off a screen into a catch-and-shoot — footwork into the shot.", cues: ["Low and tight off the screen", "1-2 into the shot"], equipment: ["ball", "hoop", "cones"], tier: "advanced", develops: ["movement_shooting", "off_screen_navigation"], cnsLoad: "moderate", regions: ["none"], dose: "10 makes / side", defaultSets: 0, progression: "Curl / flare reads", regression: "Slower, no defender" }),
  d({ id: "free-throws", name: "Pressure Free Throws", category: "shooting", description: "Routine free throws with a make-target to simulate pressure.", cues: ["Same routine every time", "Breathe, then shoot"], equipment: ["ball", "hoop"], tier: "beginner", develops: ["catch_and_shoot"], cnsLoad: "low", regions: ["none"], dose: "make 8/10 to finish", defaultSets: 0, progression: "Shoot tired, raise target", regression: "Lower target" }),

  // ================= COURT: ball-handling =================
  d({ id: "two-ball-series", name: "Two-Ball Dribbling Series", category: "ball_handling", description: "Simultaneous and alternating two-ball dribbles for control and off-hand.", cues: ["Eyes up", "Pound the ball"], equipment: ["ball"], tier: "intermediate", develops: ["handle_under_pressure"], cnsLoad: "low", regions: ["none"], dose: "6 min", defaultSets: 0, progression: "Alternating / crossover combos", regression: "One ball, single moves" }),
  d({ id: "cone-attack-series", name: "Cone Attack Series", category: "ball_handling", description: "Change-of-pace and change-of-direction moves attacking a cone.", cues: ["Change speeds", "Low and tight on the move"], equipment: ["ball", "cones"], tier: "intermediate", develops: ["handle_under_pressure", "first_step_burst"], cnsLoad: "moderate", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Into a finish or pull-up", regression: "Walk-through moves" }),
  d({ id: "pressure-dribble", name: "Live Pressure Dribbling", category: "ball_handling", description: "Keep the ball alive against a live defender applying pressure.", cues: ["Protect with your body", "Change of pace"], equipment: ["ball", "partner"], tier: "advanced", develops: ["handle_under_pressure"], cnsLoad: "moderate", regions: ["none"], dose: "5 × 30s", defaultSets: 5, progression: "Two defenders / confined space", regression: "Token pressure" }),
  d({ id: "stationary-combos", name: "Stationary Combo Dribbling", category: "ball_handling", description: "Crossovers, between-legs, behind-the-back combos for hand speed.", cues: ["Snap the ball", "Stay low"], equipment: ["ball"], tier: "beginner", develops: ["handle_under_pressure"], cnsLoad: "low", regions: ["none"], dose: "6 min", defaultSets: 0, progression: "Add tennis-ball toss", regression: "Single moves, slower" }),

  // ================= COURT: finishing =================
  d({ id: "mikan-series", name: "Mikan Series", category: "finishing", description: "Both-hand rhythm finishing at the rim — footwork and touch.", cues: ["Soft off the glass", "Alternate hands"], equipment: ["ball", "hoop"], tier: "beginner", develops: ["rim_finishing"], cnsLoad: "low", regions: ["none"], dose: "40 makes", defaultSets: 0, progression: "Reverse Mikan", regression: "Slower, closer" }),
  d({ id: "off-both-feet", name: "Finish Off Both Feet", category: "finishing", description: "Layups off one foot and two feet, both hands, both sides.", cues: ["Long last stride vs. gather", "Protect the ball high"], equipment: ["ball", "hoop"], tier: "intermediate", develops: ["rim_finishing", "first_step_burst"], cnsLoad: "moderate", regions: ["knee", "ankle"], dose: "10 / hand / footwork", defaultSets: 0, progression: "Add a pad for contact", regression: "No defender, half speed" }),
  d({ id: "contact-finishing", name: "Contact Finishing", category: "finishing", description: "Absorb contact and finish through a pad — strength through the rim.", cues: ["Go into the contact", "Finish high and strong"], equipment: ["ball", "hoop", "partner"], tier: "advanced", develops: ["rim_finishing", "strength_mass"], cnsLoad: "moderate", regions: ["none"], dose: "8 / side", defaultSets: 0, progression: "Late contact, tougher angles", regression: "Lighter contact" }),
  d({ id: "floater-series", name: "Floater & Pro-Hop Series", category: "finishing", description: "In-between game — floaters, Euros, and pro-hops off two dribbles.", cues: ["High off soft touch", "Read the big early"], equipment: ["ball", "hoop"], tier: "advanced", develops: ["floater_short_mid", "rim_finishing"], cnsLoad: "moderate", regions: ["none"], dose: "10 makes / move", defaultSets: 0, progression: "Off live reads", regression: "Set-spot floaters" }),

  // ================= COURT: footwork =================
  d({ id: "pivot-series", name: "Pivot & Step-Through Series", category: "footwork", description: "Front and reverse pivots into step-throughs off the catch.", cues: ["Stay low", "Pivot foot stays planted"], equipment: ["ball"], tier: "beginner", develops: ["post_scoring", "handle_under_pressure"], cnsLoad: "low", regions: ["none"], dose: "6 min", defaultSets: 0, progression: "Into a shot or drive", regression: "Slow, no ball" }),
  d({ id: "1-2-vs-hop", name: "1-2 Step vs. Hop Footwork", category: "footwork", description: "Getting into the shot two ways off the catch and off the dribble.", cues: ["Consistent gather", "Balanced base"], equipment: ["ball", "hoop"], tier: "intermediate", develops: ["catch_and_shoot", "off_dribble_shooting"], cnsLoad: "low", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Off movement", regression: "Stationary" }),
  d({ id: "jab-series", name: "Jab Step Series", category: "footwork", description: "Jab, jab-and-go, jab-and-shoot to create space from a triple-threat.", cues: ["Sell the jab", "Read the defender's hips"], equipment: ["ball", "hoop"], tier: "intermediate", develops: ["off_dribble_shooting", "first_step_burst"], cnsLoad: "low", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Live defender", regression: "No defender, slow" }),

  // ================= COURT: decision-making =================
  d({ id: "pnr-reads", name: "Pick-and-Roll Reads", category: "decision_making", description: "Read the coverage — reject, split, snake, or hit the roller.", cues: ["Read the big's level", "Two-foot into the read"], equipment: ["ball", "hoop", "partner"], tier: "advanced", develops: ["passing_vision", "off_ball_iq", "handle_under_pressure"], cnsLoad: "moderate", regions: ["none"], dose: "10 min", defaultSets: 0, progression: "Add a second defender", regression: "Scripted single coverage" }),
  d({ id: "short-roll-passing", name: "Short-Roll Passing", category: "decision_making", description: "Make the 4-on-3 read out of the short roll — pocket, skip, lob.", cues: ["Catch on the move", "Make the next pass"], equipment: ["ball", "hoop", "partner"], tier: "advanced", develops: ["passing_vision", "off_ball_iq"], cnsLoad: "low", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Live help defender", regression: "Read a coach's cue" }),
  d({ id: "advantage-drill", name: "Advantage / Close-Out Reads", category: "decision_making", description: "Attack a closeout — shoot, drive, or swing to keep the advantage.", cues: ["Attack the high shoulder", "0.5-second decision"], equipment: ["ball", "hoop", "partner"], tier: "intermediate", develops: ["off_ball_iq", "off_dribble_shooting", "passing_vision"], cnsLoad: "moderate", regions: ["none"], dose: "10 min", defaultSets: 0, progression: "2-on-1, 3-on-2", regression: "Live closeout, no help" }),

  // ================= COURT: defense =================
  d({ id: "closeout-drill", name: "Closeout & Contain", category: "defense", description: "Sprint-to-closeout under control, then contain the drive.", cues: ["Chop the feet late", "High hand, low base"], equipment: ["court"], tier: "beginner", develops: ["poa_containment", "lateral_slides"], cnsLoad: "moderate", regions: ["knee", "ankle"], dose: "6 min", defaultSets: 0, progression: "Live 1-on-1 closeout", regression: "Shadow, no ball" }),
  d({ id: "slide-series", name: "Defensive Slide Series", category: "defense", description: "Lateral slides through a pattern — hips low, no crossing the feet.", cues: ["Stay low", "Push off the trail foot"], equipment: ["cones"], tier: "beginner", develops: ["lateral_slides", "poa_containment"], cnsLoad: "moderate", regions: ["knee", "hip"], dose: "5 × 30s", defaultSets: 5, progression: "Reactive on the point", regression: "Slower, shorter" }),
  d({ id: "screen-nav", name: "Screen Navigation", category: "defense", description: "Fight over and under ball screens, staying attached.", cues: ["Get skinny", "Beat the ball to the spot"], equipment: ["court", "partner"], tier: "advanced", develops: ["def_screen_navigation", "poa_containment"], cnsLoad: "moderate", regions: ["none"], dose: "8 min", defaultSets: 0, progression: "Live pick-and-roll", regression: "Walk-through" }),
  d({ id: "rebounding-position", name: "Box-Out & Rebound", category: "defense", description: "Find, hit, and pursue — contested rebounding discipline.", cues: ["Make contact first", "Chin the ball"], equipment: ["ball", "hoop", "partner"], tier: "beginner", develops: ["rebounding", "strength_mass"], cnsLoad: "moderate", regions: ["none"], dose: "6 min", defaultSets: 0, progression: "2-on-2 box-out war", regression: "Uncontested" }),

  // ================= COURT: live reps =================
  d({ id: "1v1-live", name: "1-on-1 from the Wing", category: "live_reps", description: "Live one-on-one with a rep and score target — apply the day's work.", cues: ["Play to your counters", "Finish the possession"], equipment: ["ball", "hoop", "partner"], tier: "intermediate", develops: ["handle_under_pressure", "poa_containment", "rim_finishing"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "first to 7, best of 3", defaultSets: 0, progression: "Start from a live dribble", regression: "Limit dribbles, half speed" }),
  d({ id: "2v2-live", name: "2-on-2 Reads", category: "live_reps", description: "Small-sided game to apply pick-and-roll and off-ball reads live.", cues: ["Play off two feet", "Talk on defense"], equipment: ["ball", "hoop", "partner"], tier: "advanced", develops: ["passing_vision", "off_ball_iq", "def_screen_navigation"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "4 × 4 min", defaultSets: 0, progression: "3-on-3 full reads", regression: "Guided, coach-paused" }),
  d({ id: "full-runs", name: "Full-Court Runs", category: "live_reps", description: "Live 5-on-5 or open runs — conditioning and decisions under fatigue.", cues: ["Compete every possession", "Habits under fatigue"], equipment: ["ball", "hoop", "court", "partner"], tier: "elite", develops: ["endurance", "off_ball_iq", "handle_under_pressure"], cnsLoad: "high", regions: ["knee", "ankle"], dose: "target 20 min live", defaultSets: 0, progression: "Track plus/minus", regression: "Half-court, fewer reps" }),
];

// Guard against a duplicate id sneaking in.
const seen = new Set<string>();
for (const dr of DRILLS) {
  if (seen.has(dr.id)) throw new Error(`Duplicate drill id: ${dr.id}`);
  seen.add(dr.id);
}

export const DRILLS_BY_ID: Record<string, Drill> = Object.fromEntries(DRILLS.map((x) => [x.id, x]));
