/**
 * Seed archetype library (spec Part 2.2): 32 stylistic molds.
 *
 * These are hand-authored stylistic TEMPLATES, not live-stat snapshots. The
 * spec asked to "verify current-season accuracy against a live source" — I
 * pushed back in Phase 0: archetypes are style patterns and do not depend on
 * this season's numbers, so there is deliberately no live data dependency here.
 * (Live sourcing lives in the Shoe catalog, where it genuinely matters.)
 *
 * DNA values are 0-100. `vec()` fills any unlisted dimension with 50 (average),
 * so each definition only spells out its salient dimensions. The `developmental`
 * archetypes are the "be honest about the level" molds the spec called for.
 */

import { vec } from "../dna/vector";
import type { Archetype, TrainingEmphasis } from "./types";

/** Training-emphasis helper: everything defaults to 0.3, override the salient focuses. */
function emph(overrides: Partial<TrainingEmphasis>): TrainingEmphasis {
  return {
    shooting: 0.3,
    finishing: 0.3,
    ballhandling: 0.3,
    playmaking: 0.3,
    perimeterDefense: 0.3,
    interiorDefense: 0.3,
    strength: 0.3,
    power: 0.3,
    speedAgility: 0.3,
    conditioning: 0.3,
    ...overrides,
  };
}

export const ARCHETYPES: Archetype[] = [
  // ============================ GUARDS ============================
  {
    id: "movement-shooter",
    name: "Movement Shooter / Gravity Guard",
    blurb: "Elite off-movement shooting bends the defense before the ball moves.",
    nbaReference: "Stephen Curry",
    collegeReference: "Stephen Curry (Davidson)",
    buildRange: "6'0\"–6'4\", lean, elite conditioning",
    dna: vec({
      height_percentile: 45, wingspan_ratio: 35, standing_reach: 40, vertical_explosiveness: 55,
      lateral_quickness: 70, first_step_burst: 68, strength_mass: 38, endurance: 93,
      catch_and_shoot: 96, off_dribble_shooting: 97, movement_shooting: 99, rim_finishing: 72,
      floater_short_mid: 82, post_scoring: 22, handle_under_pressure: 92, passing_vision: 85,
      off_screen_navigation: 96, off_ball_iq: 95, poa_containment: 45, lateral_slides: 60,
      def_screen_navigation: 55, rim_protection: 15, help_rotations: 55, rebounding: 33, steal_deflection: 78,
      pace_preference: 75, shot_location: 90, on_off_ball: 58, iso_vs_system: 42, physicality_tolerance: 42,
    }),
    definingSkills: ["movement_shooting", "off_dribble_shooting", "catch_and_shoot", "off_screen_navigation", "handle_under_pressure"],
    commonWeaknesses: ["strength_mass", "rim_protection", "poa_containment", "rebounding", "post_scoring"],
    trainingEmphasis: emph({ shooting: 0.95, ballhandling: 0.7, conditioning: 0.8, speedAgility: 0.6, playmaking: 0.5, strength: 0.5 }),
  },
  {
    id: "downhill-athletic-pg",
    name: "Downhill Athletic PG",
    blurb: "Lives in the paint off elite burst and vertical pop.",
    nbaReference: "Ja Morant",
    collegeReference: "Ja Morant (Murray State)",
    buildRange: "6'2\"–6'5\", explosive, plus wingspan",
    dna: vec({
      height_percentile: 55, wingspan_ratio: 78, standing_reach: 60, vertical_explosiveness: 95,
      lateral_quickness: 82, first_step_burst: 96, strength_mass: 48, endurance: 80,
      catch_and_shoot: 60, off_dribble_shooting: 66, movement_shooting: 44, rim_finishing: 94,
      floater_short_mid: 80, post_scoring: 28, handle_under_pressure: 90, passing_vision: 88,
      off_screen_navigation: 52, off_ball_iq: 58, poa_containment: 58, lateral_slides: 72,
      def_screen_navigation: 48, rim_protection: 30, help_rotations: 50, rebounding: 45, steal_deflection: 70,
      pace_preference: 93, shot_location: 40, on_off_ball: 85, iso_vs_system: 62, physicality_tolerance: 55,
    }),
    definingSkills: ["first_step_burst", "vertical_explosiveness", "rim_finishing", "handle_under_pressure", "passing_vision"],
    commonWeaknesses: ["movement_shooting", "rim_protection", "def_screen_navigation", "off_ball_iq", "catch_and_shoot"],
    trainingEmphasis: emph({ finishing: 0.85, ballhandling: 0.8, power: 0.8, speedAgility: 0.8, playmaking: 0.7, shooting: 0.65 }),
  },
  {
    id: "pnr-floor-general",
    name: "Pick-and-Roll Floor General",
    blurb: "High-IQ orchestrator who wins with reads, pace control, and touch.",
    nbaReference: "Chris Paul / Tyrese Haliburton",
    collegeReference: "Tyrese Haliburton (Iowa State)",
    buildRange: "6'0\"–6'5\", high IQ, moderate athleticism",
    dna: vec({
      height_percentile: 52, wingspan_ratio: 60, standing_reach: 52, vertical_explosiveness: 45,
      lateral_quickness: 66, first_step_burst: 60, strength_mass: 50, endurance: 82,
      catch_and_shoot: 82, off_dribble_shooting: 84, movement_shooting: 66, rim_finishing: 68,
      floater_short_mid: 92, post_scoring: 30, handle_under_pressure: 90, passing_vision: 97,
      off_screen_navigation: 62, off_ball_iq: 82, poa_containment: 66, lateral_slides: 62,
      def_screen_navigation: 66, rim_protection: 20, help_rotations: 68, rebounding: 40, steal_deflection: 80,
      pace_preference: 55, shot_location: 65, on_off_ball: 82, iso_vs_system: 40, physicality_tolerance: 45,
    }),
    definingSkills: ["passing_vision", "handle_under_pressure", "floater_short_mid", "off_dribble_shooting", "off_ball_iq"],
    commonWeaknesses: ["vertical_explosiveness", "rim_protection", "rebounding", "first_step_burst", "post_scoring"],
    trainingEmphasis: emph({ playmaking: 0.95, ballhandling: 0.8, shooting: 0.75, perimeterDefense: 0.6, conditioning: 0.6, finishing: 0.5 }),
  },
  {
    id: "two-way-poa-guard",
    name: "Two-Way Point-of-Attack Guard",
    blurb: "Dense, strong guard who defends the ball and scores at three levels.",
    nbaReference: "Jrue Holiday",
    collegeReference: "Jrue Holiday (UCLA)",
    buildRange: "6'3\"–6'5\", dense frame, strong",
    dna: vec({
      height_percentile: 58, wingspan_ratio: 70, standing_reach: 58, vertical_explosiveness: 68,
      lateral_quickness: 84, first_step_burst: 74, strength_mass: 78, endurance: 82,
      catch_and_shoot: 80, off_dribble_shooting: 76, movement_shooting: 62, rim_finishing: 80,
      floater_short_mid: 74, post_scoring: 45, handle_under_pressure: 82, passing_vision: 80,
      off_screen_navigation: 60, off_ball_iq: 72, poa_containment: 94, lateral_slides: 90,
      def_screen_navigation: 82, rim_protection: 35, help_rotations: 78, rebounding: 55, steal_deflection: 85,
      pace_preference: 55, shot_location: 55, on_off_ball: 68, iso_vs_system: 50, physicality_tolerance: 80,
    }),
    definingSkills: ["poa_containment", "lateral_slides", "steal_deflection", "strength_mass", "def_screen_navigation"],
    commonWeaknesses: ["movement_shooting", "rim_protection", "post_scoring", "off_screen_navigation", "off_ball_iq"],
    trainingEmphasis: emph({ perimeterDefense: 0.95, strength: 0.75, shooting: 0.65, ballhandling: 0.6, finishing: 0.6, speedAgility: 0.6 }),
  },
  {
    id: "three-level-scoring-guard",
    name: "Three-Level Scoring Guard",
    blurb: "Powerful base, scores from the rim, mid, and deep with volume.",
    nbaReference: "Donovan Mitchell / Devin Booker",
    collegeReference: "Donovan Mitchell (Louisville)",
    buildRange: "6'3\"–6'6\", powerful base",
    dna: vec({
      height_percentile: 60, wingspan_ratio: 72, standing_reach: 60, vertical_explosiveness: 82,
      lateral_quickness: 72, first_step_burst: 82, strength_mass: 72, endurance: 82,
      catch_and_shoot: 86, off_dribble_shooting: 90, movement_shooting: 78, rim_finishing: 86,
      floater_short_mid: 84, post_scoring: 48, handle_under_pressure: 86, passing_vision: 72,
      off_screen_navigation: 78, off_ball_iq: 70, poa_containment: 62, lateral_slides: 66,
      def_screen_navigation: 58, rim_protection: 28, help_rotations: 55, rebounding: 45, steal_deflection: 70,
      pace_preference: 65, shot_location: 60, on_off_ball: 78, iso_vs_system: 68, physicality_tolerance: 62,
    }),
    definingSkills: ["off_dribble_shooting", "catch_and_shoot", "rim_finishing", "handle_under_pressure", "floater_short_mid"],
    commonWeaknesses: ["poa_containment", "passing_vision", "rim_protection", "help_rotations", "def_screen_navigation"],
    trainingEmphasis: emph({ shooting: 0.9, finishing: 0.75, ballhandling: 0.75, power: 0.65, perimeterDefense: 0.5, playmaking: 0.5 }),
  },
  {
    id: "undersized-combo-scorer",
    name: "Undersized Combo Scorer",
    blurb: "Wins with shot volume, craft, and strength despite lacking size.",
    nbaReference: "Fred VanVleet",
    collegeReference: "Fred VanVleet (Wichita State)",
    buildRange: "5'11\"–6'2\", high shot volume, strength-dependent",
    dna: vec({
      height_percentile: 25, wingspan_ratio: 55, standing_reach: 28, vertical_explosiveness: 55,
      lateral_quickness: 78, first_step_burst: 70, strength_mass: 66, endurance: 84,
      catch_and_shoot: 84, off_dribble_shooting: 86, movement_shooting: 74, rim_finishing: 60,
      floater_short_mid: 78, post_scoring: 20, handle_under_pressure: 88, passing_vision: 82,
      off_screen_navigation: 70, off_ball_iq: 74, poa_containment: 78, lateral_slides: 78,
      def_screen_navigation: 60, rim_protection: 12, help_rotations: 60, rebounding: 35, steal_deflection: 82,
      pace_preference: 55, shot_location: 70, on_off_ball: 72, iso_vs_system: 55, physicality_tolerance: 70,
    }),
    definingSkills: ["off_dribble_shooting", "handle_under_pressure", "poa_containment", "steal_deflection", "catch_and_shoot"],
    commonWeaknesses: ["height_percentile", "standing_reach", "rim_protection", "rim_finishing", "rebounding"],
    trainingEmphasis: emph({ shooting: 0.9, ballhandling: 0.8, perimeterDefense: 0.7, strength: 0.7, conditioning: 0.6, playmaking: 0.5 }),
  },
  {
    id: "microwave-shot-creator",
    name: "Microwave Shot-Creator",
    blurb: "Instant offense off the bounce, elite self-creation in isolation.",
    nbaReference: "Jamal Murray",
    collegeReference: "Jamal Murray (Kentucky)",
    buildRange: "6'3\"–6'5\", smooth, shifty",
    dna: vec({
      height_percentile: 55, wingspan_ratio: 58, standing_reach: 55, vertical_explosiveness: 62,
      lateral_quickness: 70, first_step_burst: 74, strength_mass: 58, endurance: 78,
      catch_and_shoot: 84, off_dribble_shooting: 92, movement_shooting: 76, rim_finishing: 74,
      floater_short_mid: 86, post_scoring: 40, handle_under_pressure: 90, passing_vision: 78,
      off_screen_navigation: 72, off_ball_iq: 68, poa_containment: 55, lateral_slides: 58,
      def_screen_navigation: 52, rim_protection: 22, help_rotations: 50, rebounding: 40, steal_deflection: 62,
      pace_preference: 60, shot_location: 62, on_off_ball: 78, iso_vs_system: 72, physicality_tolerance: 52,
    }),
    definingSkills: ["off_dribble_shooting", "handle_under_pressure", "floater_short_mid", "movement_shooting", "catch_and_shoot"],
    commonWeaknesses: ["poa_containment", "lateral_slides", "rim_protection", "rebounding", "help_rotations"],
    trainingEmphasis: emph({ shooting: 0.9, ballhandling: 0.85, finishing: 0.6, playmaking: 0.55, perimeterDefense: 0.5, speedAgility: 0.5 }),
  },
  {
    id: "defensive-pest-guard",
    name: "Defensive Pest Guard",
    blurb: "Ball-hawking, physical on-ball menace who sets the defensive tone.",
    nbaReference: "Marcus Smart",
    collegeReference: "Marcus Smart (Oklahoma State)",
    buildRange: "6'2\"–6'4\", strong, high motor",
    dna: vec({
      height_percentile: 50, wingspan_ratio: 74, standing_reach: 52, vertical_explosiveness: 60,
      lateral_quickness: 88, first_step_burst: 66, strength_mass: 80, endurance: 86,
      catch_and_shoot: 66, off_dribble_shooting: 58, movement_shooting: 52, rim_finishing: 62,
      floater_short_mid: 55, post_scoring: 35, handle_under_pressure: 74, passing_vision: 78,
      off_screen_navigation: 55, off_ball_iq: 70, poa_containment: 96, lateral_slides: 94,
      def_screen_navigation: 88, rim_protection: 32, help_rotations: 86, rebounding: 58, steal_deflection: 92,
      pace_preference: 58, shot_location: 55, on_off_ball: 62, iso_vs_system: 45, physicality_tolerance: 90,
    }),
    definingSkills: ["poa_containment", "lateral_slides", "steal_deflection", "def_screen_navigation", "help_rotations"],
    commonWeaknesses: ["off_dribble_shooting", "catch_and_shoot", "rim_finishing", "post_scoring", "movement_shooting"],
    trainingEmphasis: emph({ perimeterDefense: 0.95, strength: 0.75, shooting: 0.7, conditioning: 0.65, ballhandling: 0.5, speedAgility: 0.6 }),
  },
  {
    id: "pace-and-space-lead-guard",
    name: "Pace-and-Space Lead Guard",
    blurb: "Deep range plus advantage passing warps the entire floor.",
    nbaReference: "Trae Young",
    collegeReference: "Trae Young (Oklahoma)",
    buildRange: "6'0\"–6'3\", skilled, average length",
    dna: vec({
      height_percentile: 40, wingspan_ratio: 45, standing_reach: 40, vertical_explosiveness: 48,
      lateral_quickness: 60, first_step_burst: 66, strength_mass: 42, endurance: 80,
      catch_and_shoot: 88, off_dribble_shooting: 94, movement_shooting: 70, rim_finishing: 64,
      floater_short_mid: 90, post_scoring: 20, handle_under_pressure: 90, passing_vision: 96,
      off_screen_navigation: 62, off_ball_iq: 66, poa_containment: 38, lateral_slides: 44,
      def_screen_navigation: 40, rim_protection: 12, help_rotations: 45, rebounding: 30, steal_deflection: 62,
      pace_preference: 78, shot_location: 72, on_off_ball: 88, iso_vs_system: 60, physicality_tolerance: 38,
    }),
    definingSkills: ["passing_vision", "off_dribble_shooting", "floater_short_mid", "handle_under_pressure", "catch_and_shoot"],
    commonWeaknesses: ["poa_containment", "lateral_slides", "strength_mass", "rim_protection", "rebounding"],
    trainingEmphasis: emph({ shooting: 0.9, playmaking: 0.9, ballhandling: 0.8, perimeterDefense: 0.6, strength: 0.55, conditioning: 0.5 }),
  },

  // ============================ WINGS ============================
  {
    id: "three-and-d-wing",
    name: "3&D Wing",
    blurb: "Long, low-mistake wing who guards up positions and knocks down catch-and-shoot.",
    nbaReference: "Mikal Bridges / OG Anunoby",
    collegeReference: "Mikal Bridges (Villanova)",
    buildRange: "6'5\"–6'8\", huge wingspan",
    dna: vec({
      height_percentile: 62, wingspan_ratio: 90, standing_reach: 72, vertical_explosiveness: 70,
      lateral_quickness: 82, first_step_burst: 68, strength_mass: 62, endurance: 88,
      catch_and_shoot: 84, off_dribble_shooting: 60, movement_shooting: 66, rim_finishing: 74,
      floater_short_mid: 58, post_scoring: 40, handle_under_pressure: 58, passing_vision: 60,
      off_screen_navigation: 66, off_ball_iq: 78, poa_containment: 90, lateral_slides: 86,
      def_screen_navigation: 82, rim_protection: 52, help_rotations: 82, rebounding: 58, steal_deflection: 84,
      pace_preference: 55, shot_location: 68, on_off_ball: 40, iso_vs_system: 35, physicality_tolerance: 66,
    }),
    definingSkills: ["poa_containment", "catch_and_shoot", "lateral_slides", "steal_deflection", "off_ball_iq"],
    commonWeaknesses: ["off_dribble_shooting", "handle_under_pressure", "passing_vision", "post_scoring", "floater_short_mid"],
    trainingEmphasis: emph({ perimeterDefense: 0.9, shooting: 0.8, conditioning: 0.7, ballhandling: 0.55, finishing: 0.5, speedAgility: 0.6 }),
  },
  {
    id: "iso-scoring-wing",
    name: "Isolation Scoring Wing",
    blurb: "Big, strong three-level shot-maker who thrives in one-on-one.",
    nbaReference: "Jayson Tatum / Kawhi Leonard",
    collegeReference: "Jayson Tatum (Duke)",
    buildRange: "6'6\"–6'9\", strong, three-level",
    dna: vec({
      height_percentile: 72, wingspan_ratio: 80, standing_reach: 74, vertical_explosiveness: 76,
      lateral_quickness: 70, first_step_burst: 74, strength_mass: 74, endurance: 84,
      catch_and_shoot: 84, off_dribble_shooting: 88, movement_shooting: 72, rim_finishing: 82,
      floater_short_mid: 84, post_scoring: 68, handle_under_pressure: 82, passing_vision: 72,
      off_screen_navigation: 70, off_ball_iq: 72, poa_containment: 74, lateral_slides: 72,
      def_screen_navigation: 70, rim_protection: 48, help_rotations: 68, rebounding: 66, steal_deflection: 72,
      pace_preference: 52, shot_location: 58, on_off_ball: 72, iso_vs_system: 78, physicality_tolerance: 70,
    }),
    definingSkills: ["off_dribble_shooting", "post_scoring", "floater_short_mid", "rim_finishing", "handle_under_pressure"],
    commonWeaknesses: ["passing_vision", "def_screen_navigation", "pace_preference", "help_rotations", "rim_protection"],
    trainingEmphasis: emph({ shooting: 0.85, finishing: 0.75, ballhandling: 0.7, strength: 0.65, perimeterDefense: 0.6, playmaking: 0.5 }),
  },
  {
    id: "slashing-athletic-wing",
    name: "Slashing Athletic Wing",
    blurb: "Powerful downhill scorer and above-the-rim finisher.",
    nbaReference: "Anthony Edwards",
    collegeReference: "Anthony Edwards (Georgia)",
    buildRange: "6'4\"–6'7\", explosive, strong",
    dna: vec({
      height_percentile: 60, wingspan_ratio: 78, standing_reach: 64, vertical_explosiveness: 94,
      lateral_quickness: 78, first_step_burst: 90, strength_mass: 80, endurance: 82,
      catch_and_shoot: 74, off_dribble_shooting: 76, movement_shooting: 58, rim_finishing: 92,
      floater_short_mid: 66, post_scoring: 48, handle_under_pressure: 74, passing_vision: 64,
      off_screen_navigation: 58, off_ball_iq: 60, poa_containment: 74, lateral_slides: 76,
      def_screen_navigation: 62, rim_protection: 45, help_rotations: 58, rebounding: 60, steal_deflection: 76,
      pace_preference: 72, shot_location: 50, on_off_ball: 72, iso_vs_system: 66, physicality_tolerance: 78,
    }),
    definingSkills: ["vertical_explosiveness", "first_step_burst", "rim_finishing", "strength_mass", "off_dribble_shooting"],
    commonWeaknesses: ["movement_shooting", "passing_vision", "off_ball_iq", "def_screen_navigation", "floater_short_mid"],
    trainingEmphasis: emph({ finishing: 0.85, power: 0.85, shooting: 0.7, speedAgility: 0.75, ballhandling: 0.65, perimeterDefense: 0.6 }),
  },
  {
    id: "movement-shooting-wing",
    name: "Movement-Shooting Wing",
    blurb: "Sprints off screens for catch-and-shoot threes; relentless relocation.",
    nbaReference: "Klay Thompson",
    collegeReference: "Klay Thompson (Washington State)",
    buildRange: "6'5\"–6'7\", lean, high-endurance",
    dna: vec({
      height_percentile: 62, wingspan_ratio: 66, standing_reach: 64, vertical_explosiveness: 58,
      lateral_quickness: 70, first_step_burst: 58, strength_mass: 58, endurance: 92,
      catch_and_shoot: 96, off_dribble_shooting: 72, movement_shooting: 95, rim_finishing: 66,
      floater_short_mid: 62, post_scoring: 42, handle_under_pressure: 58, passing_vision: 56,
      off_screen_navigation: 96, off_ball_iq: 90, poa_containment: 76, lateral_slides: 72,
      def_screen_navigation: 78, rim_protection: 40, help_rotations: 70, rebounding: 50, steal_deflection: 64,
      pace_preference: 55, shot_location: 72, on_off_ball: 38, iso_vs_system: 35, physicality_tolerance: 58,
    }),
    definingSkills: ["catch_and_shoot", "movement_shooting", "off_screen_navigation", "off_ball_iq", "poa_containment"],
    commonWeaknesses: ["handle_under_pressure", "passing_vision", "off_dribble_shooting", "post_scoring", "rebounding"],
    trainingEmphasis: emph({ shooting: 0.95, conditioning: 0.8, perimeterDefense: 0.6, speedAgility: 0.6, ballhandling: 0.45, finishing: 0.45 }),
  },
  {
    id: "connector-playmaking-forward",
    name: "Connector / Secondary Playmaking Forward",
    blurb: "Skilled, versatile forward who keeps the offense flowing.",
    nbaReference: "Franz Wagner",
    collegeReference: "Franz Wagner (Michigan)",
    buildRange: "6'7\"–6'10\", skilled, versatile",
    dna: vec({
      height_percentile: 74, wingspan_ratio: 72, standing_reach: 74, vertical_explosiveness: 62,
      lateral_quickness: 66, first_step_burst: 66, strength_mass: 66, endurance: 84,
      catch_and_shoot: 78, off_dribble_shooting: 72, movement_shooting: 68, rim_finishing: 80,
      floater_short_mid: 74, post_scoring: 58, handle_under_pressure: 76, passing_vision: 84,
      off_screen_navigation: 66, off_ball_iq: 82, poa_containment: 72, lateral_slides: 68,
      def_screen_navigation: 72, rim_protection: 50, help_rotations: 80, rebounding: 68, steal_deflection: 72,
      pace_preference: 58, shot_location: 55, on_off_ball: 60, iso_vs_system: 42, physicality_tolerance: 64,
    }),
    definingSkills: ["passing_vision", "off_ball_iq", "rim_finishing", "handle_under_pressure", "help_rotations"],
    commonWeaknesses: ["vertical_explosiveness", "movement_shooting", "post_scoring", "first_step_burst", "rim_protection"],
    trainingEmphasis: emph({ playmaking: 0.85, ballhandling: 0.7, shooting: 0.7, finishing: 0.6, perimeterDefense: 0.6, strength: 0.55 }),
  },
  {
    id: "two-way-do-it-all-forward",
    name: "Two-Way Do-It-All Forward",
    blurb: "Positionless two-way engine who impacts every phase of the game.",
    nbaReference: "Cooper Flagg (projection)",
    collegeReference: "Cooper Flagg (Duke)",
    buildRange: "6'8\"–6'9\", positionless",
    dna: vec({
      height_percentile: 76, wingspan_ratio: 78, standing_reach: 78, vertical_explosiveness: 80,
      lateral_quickness: 78, first_step_burst: 74, strength_mass: 68, endurance: 86,
      catch_and_shoot: 76, off_dribble_shooting: 72, movement_shooting: 66, rim_finishing: 82,
      floater_short_mid: 70, post_scoring: 60, handle_under_pressure: 74, passing_vision: 80,
      off_screen_navigation: 66, off_ball_iq: 82, poa_containment: 82, lateral_slides: 80,
      def_screen_navigation: 78, rim_protection: 74, help_rotations: 86, rebounding: 80, steal_deflection: 84,
      pace_preference: 62, shot_location: 52, on_off_ball: 58, iso_vs_system: 48, physicality_tolerance: 76,
    }),
    definingSkills: ["help_rotations", "rebounding", "steal_deflection", "poa_containment", "off_ball_iq"],
    commonWeaknesses: ["off_dribble_shooting", "post_scoring", "movement_shooting", "floater_short_mid", "handle_under_pressure"],
    trainingEmphasis: emph({ perimeterDefense: 0.8, shooting: 0.75, finishing: 0.65, interiorDefense: 0.65, power: 0.6, playmaking: 0.6 }),
  },
  {
    id: "point-forward-rim-pressure",
    name: "Point Forward / Rim Pressure",
    blurb: "Elite length and burst attack the basket and create for others.",
    nbaReference: "Giannis Antetokounmpo",
    collegeReference: "Ben Simmons (LSU)",
    buildRange: "6'9\"+, elite length and burst",
    dna: vec({
      height_percentile: 88, wingspan_ratio: 92, standing_reach: 90, vertical_explosiveness: 92,
      lateral_quickness: 74, first_step_burst: 90, strength_mass: 84, endurance: 88,
      catch_and_shoot: 46, off_dribble_shooting: 42, movement_shooting: 30, rim_finishing: 96,
      floater_short_mid: 58, post_scoring: 74, handle_under_pressure: 72, passing_vision: 82,
      off_screen_navigation: 44, off_ball_iq: 66, poa_containment: 78, lateral_slides: 74,
      def_screen_navigation: 66, rim_protection: 82, help_rotations: 84, rebounding: 86, steal_deflection: 74,
      pace_preference: 78, shot_location: 30, on_off_ball: 78, iso_vs_system: 58, physicality_tolerance: 88,
    }),
    definingSkills: ["rim_finishing", "first_step_burst", "vertical_explosiveness", "rebounding", "passing_vision"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "movement_shooting", "floater_short_mid", "off_screen_navigation"],
    trainingEmphasis: emph({ shooting: 0.85, finishing: 0.7, interiorDefense: 0.7, power: 0.65, playmaking: 0.6, strength: 0.6 }),
  },
  {
    id: "wing-stopper",
    name: "Low-Usage Wing Stopper",
    blurb: "Defends the best perimeter scorer nightly; scores within the offense.",
    nbaReference: "OG Anunoby / Herbert Jones",
    collegeReference: "Herbert Jones (Alabama)",
    buildRange: "6'6\"–6'8\", strong, huge hands and length",
    dna: vec({
      height_percentile: 64, wingspan_ratio: 88, standing_reach: 72, vertical_explosiveness: 72,
      lateral_quickness: 86, first_step_burst: 66, strength_mass: 72, endurance: 88,
      catch_and_shoot: 74, off_dribble_shooting: 52, movement_shooting: 56, rim_finishing: 72,
      floater_short_mid: 50, post_scoring: 44, handle_under_pressure: 52, passing_vision: 62,
      off_screen_navigation: 58, off_ball_iq: 78, poa_containment: 94, lateral_slides: 92,
      def_screen_navigation: 86, rim_protection: 58, help_rotations: 86, rebounding: 64, steal_deflection: 90,
      pace_preference: 52, shot_location: 62, on_off_ball: 34, iso_vs_system: 30, physicality_tolerance: 82,
    }),
    definingSkills: ["poa_containment", "lateral_slides", "steal_deflection", "def_screen_navigation", "help_rotations"],
    commonWeaknesses: ["off_dribble_shooting", "handle_under_pressure", "post_scoring", "floater_short_mid", "movement_shooting"],
    trainingEmphasis: emph({ perimeterDefense: 0.95, shooting: 0.75, conditioning: 0.7, strength: 0.6, finishing: 0.5, ballhandling: 0.5 }),
  },

  // ============================ BIGS ============================
  {
    id: "stretch-four",
    name: "Stretch Four",
    blurb: "Floor-spacing big forward who shoots it and attacks closeouts.",
    nbaReference: "Lauri Markkanen",
    collegeReference: "Lauri Markkanen (Arizona)",
    buildRange: "6'9\"–6'11\", mobile shooting forward",
    dna: vec({
      height_percentile: 80, wingspan_ratio: 70, standing_reach: 80, vertical_explosiveness: 66,
      lateral_quickness: 58, first_step_burst: 60, strength_mass: 64, endurance: 80,
      catch_and_shoot: 90, off_dribble_shooting: 70, movement_shooting: 74, rim_finishing: 76,
      floater_short_mid: 64, post_scoring: 58, handle_under_pressure: 58, passing_vision: 58,
      off_screen_navigation: 68, off_ball_iq: 74, poa_containment: 56, lateral_slides: 54,
      def_screen_navigation: 58, rim_protection: 50, help_rotations: 62, rebounding: 70, steal_deflection: 55,
      pace_preference: 55, shot_location: 68, on_off_ball: 44, iso_vs_system: 45, physicality_tolerance: 58,
    }),
    definingSkills: ["catch_and_shoot", "movement_shooting", "rim_finishing", "rebounding", "off_ball_iq"],
    commonWeaknesses: ["poa_containment", "lateral_slides", "handle_under_pressure", "rim_protection", "strength_mass"],
    trainingEmphasis: emph({ shooting: 0.9, finishing: 0.6, strength: 0.6, interiorDefense: 0.55, power: 0.55, speedAgility: 0.5 }),
  },
  {
    id: "playmaking-hub-big",
    name: "Playmaking Hub Big",
    blurb: "IQ- and touch-driven center who runs the offense from the elbow and post.",
    nbaReference: "Nikola Jokić",
    collegeReference: "Domantas Sabonis (Gonzaga)",
    buildRange: "6'10\"+, IQ- and touch-driven",
    dna: vec({
      height_percentile: 86, wingspan_ratio: 66, standing_reach: 86, vertical_explosiveness: 40,
      lateral_quickness: 44, first_step_burst: 44, strength_mass: 82, endurance: 78,
      catch_and_shoot: 78, off_dribble_shooting: 68, movement_shooting: 52, rim_finishing: 82,
      floater_short_mid: 84, post_scoring: 92, handle_under_pressure: 74, passing_vision: 98,
      off_screen_navigation: 48, off_ball_iq: 80, poa_containment: 46, lateral_slides: 40,
      def_screen_navigation: 52, rim_protection: 56, help_rotations: 70, rebounding: 88, steal_deflection: 78,
      pace_preference: 45, shot_location: 45, on_off_ball: 66, iso_vs_system: 52, physicality_tolerance: 80,
    }),
    definingSkills: ["passing_vision", "post_scoring", "floater_short_mid", "rebounding", "rim_finishing"],
    commonWeaknesses: ["vertical_explosiveness", "lateral_quickness", "poa_containment", "first_step_burst", "lateral_slides"],
    trainingEmphasis: emph({ playmaking: 0.9, finishing: 0.7, shooting: 0.65, strength: 0.6, interiorDefense: 0.55, speedAgility: 0.5 }),
  },
  {
    id: "switchable-defensive-anchor",
    name: "Switchable Defensive Anchor",
    blurb: "Mobile, strong big who defends 1-5 and holds up on the perimeter.",
    nbaReference: "Bam Adebayo",
    collegeReference: "Bam Adebayo (Kentucky)",
    buildRange: "6'8\"–6'10\", mobile, strong",
    dna: vec({
      height_percentile: 78, wingspan_ratio: 84, standing_reach: 82, vertical_explosiveness: 82,
      lateral_quickness: 80, first_step_burst: 68, strength_mass: 84, endurance: 86,
      catch_and_shoot: 58, off_dribble_shooting: 50, movement_shooting: 42, rim_finishing: 84,
      floater_short_mid: 68, post_scoring: 66, handle_under_pressure: 58, passing_vision: 76,
      off_screen_navigation: 46, off_ball_iq: 74, poa_containment: 84, lateral_slides: 84,
      def_screen_navigation: 80, rim_protection: 84, help_rotations: 90, rebounding: 82, steal_deflection: 76,
      pace_preference: 60, shot_location: 38, on_off_ball: 46, iso_vs_system: 40, physicality_tolerance: 86,
    }),
    definingSkills: ["poa_containment", "lateral_slides", "rim_protection", "help_rotations", "rebounding"],
    commonWeaknesses: ["catch_and_shoot", "movement_shooting", "off_dribble_shooting", "off_screen_navigation", "floater_short_mid"],
    trainingEmphasis: emph({ interiorDefense: 0.85, perimeterDefense: 0.8, shooting: 0.7, power: 0.6, finishing: 0.55, strength: 0.6 }),
  },
  {
    id: "stretch-five",
    name: "Stretch Five",
    blurb: "Floor-spacing center who pairs shooting with rim protection.",
    nbaReference: "Brook Lopez / Myles Turner",
    collegeReference: "Myles Turner (Texas)",
    buildRange: "6'10\"+, shooting + verticality",
    dna: vec({
      height_percentile: 88, wingspan_ratio: 80, standing_reach: 88, vertical_explosiveness: 58,
      lateral_quickness: 44, first_step_burst: 42, strength_mass: 74, endurance: 76,
      catch_and_shoot: 84, off_dribble_shooting: 48, movement_shooting: 56, rim_finishing: 78,
      floater_short_mid: 60, post_scoring: 62, handle_under_pressure: 44, passing_vision: 56,
      off_screen_navigation: 50, off_ball_iq: 70, poa_containment: 48, lateral_slides: 42,
      def_screen_navigation: 58, rim_protection: 88, help_rotations: 74, rebounding: 74, steal_deflection: 55,
      pace_preference: 48, shot_location: 66, on_off_ball: 38, iso_vs_system: 42, physicality_tolerance: 70,
    }),
    definingSkills: ["catch_and_shoot", "rim_protection", "rebounding", "post_scoring", "rim_finishing"],
    commonWeaknesses: ["lateral_quickness", "poa_containment", "lateral_slides", "first_step_burst", "handle_under_pressure"],
    trainingEmphasis: emph({ shooting: 0.85, interiorDefense: 0.8, finishing: 0.6, strength: 0.6, power: 0.5, speedAgility: 0.45 }),
  },
  {
    id: "rim-running-lob-threat",
    name: "Rim-Running Lob Threat",
    blurb: "Vertical spacing and elite rim protection anchor both ends.",
    nbaReference: "Rudy Gobert / Walker Kessler",
    collegeReference: "Walker Kessler (Auburn)",
    buildRange: "6'11\"+, vertical spacing",
    dna: vec({
      height_percentile: 92, wingspan_ratio: 92, standing_reach: 94, vertical_explosiveness: 80,
      lateral_quickness: 46, first_step_burst: 44, strength_mass: 78, endurance: 80,
      catch_and_shoot: 30, off_dribble_shooting: 20, movement_shooting: 18, rim_finishing: 90,
      floater_short_mid: 38, post_scoring: 54, handle_under_pressure: 30, passing_vision: 50,
      off_screen_navigation: 30, off_ball_iq: 70, poa_containment: 46, lateral_slides: 44,
      def_screen_navigation: 60, rim_protection: 96, help_rotations: 88, rebounding: 92, steal_deflection: 55,
      pace_preference: 55, shot_location: 20, on_off_ball: 30, iso_vs_system: 30, physicality_tolerance: 82,
    }),
    definingSkills: ["rim_protection", "rebounding", "rim_finishing", "vertical_explosiveness", "help_rotations"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "handle_under_pressure", "floater_short_mid", "post_scoring"],
    trainingEmphasis: emph({ interiorDefense: 0.9, finishing: 0.7, power: 0.65, strength: 0.65, conditioning: 0.55, shooting: 0.4 }),
  },
  {
    id: "post-scoring-traditional-big",
    name: "Post-Scoring Traditional Big",
    blurb: "Overwhelming size and touch score with volume in the paint.",
    nbaReference: "Zach Edey (projection)",
    collegeReference: "Zach Edey (Purdue)",
    buildRange: "6'11\"+, mass and touch",
    dna: vec({
      height_percentile: 96, wingspan_ratio: 78, standing_reach: 96, vertical_explosiveness: 42,
      lateral_quickness: 32, first_step_burst: 34, strength_mass: 92, endurance: 68,
      catch_and_shoot: 46, off_dribble_shooting: 30, movement_shooting: 22, rim_finishing: 88,
      floater_short_mid: 66, post_scoring: 94, handle_under_pressure: 38, passing_vision: 60,
      off_screen_navigation: 30, off_ball_iq: 62, poa_containment: 34, lateral_slides: 30,
      def_screen_navigation: 46, rim_protection: 82, help_rotations: 62, rebounding: 92, steal_deflection: 45,
      pace_preference: 38, shot_location: 25, on_off_ball: 40, iso_vs_system: 58, physicality_tolerance: 90,
    }),
    definingSkills: ["post_scoring", "rebounding", "strength_mass", "rim_finishing", "rim_protection"],
    commonWeaknesses: ["lateral_quickness", "poa_containment", "movement_shooting", "first_step_burst", "handle_under_pressure"],
    trainingEmphasis: emph({ interiorDefense: 0.75, finishing: 0.7, strength: 0.7, conditioning: 0.6, speedAgility: 0.55, shooting: 0.5 }),
  },
  {
    id: "rebounding-energy-big",
    name: "Rebounding Energy Big",
    blurb: "Screen-and-roll, offensive glass, and physicality without needing plays.",
    nbaReference: "Steven Adams",
    collegeReference: "Steven Adams (Pittsburgh)",
    buildRange: "6'11\"+, powerful, high motor",
    dna: vec({
      height_percentile: 90, wingspan_ratio: 78, standing_reach: 90, vertical_explosiveness: 56,
      lateral_quickness: 48, first_step_burst: 46, strength_mass: 94, endurance: 82,
      catch_and_shoot: 24, off_dribble_shooting: 18, movement_shooting: 15, rim_finishing: 80,
      floater_short_mid: 40, post_scoring: 60, handle_under_pressure: 34, passing_vision: 62,
      off_screen_navigation: 28, off_ball_iq: 68, poa_containment: 52, lateral_slides: 48,
      def_screen_navigation: 64, rim_protection: 66, help_rotations: 72, rebounding: 96, steal_deflection: 60,
      pace_preference: 50, shot_location: 22, on_off_ball: 34, iso_vs_system: 30, physicality_tolerance: 96,
    }),
    definingSkills: ["rebounding", "strength_mass", "physicality_tolerance", "help_rotations", "rim_finishing"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "movement_shooting", "floater_short_mid", "handle_under_pressure"],
    trainingEmphasis: emph({ strength: 0.8, interiorDefense: 0.7, finishing: 0.6, power: 0.6, conditioning: 0.6, shooting: 0.4 }),
  },
  {
    id: "face-up-power-forward",
    name: "Face-Up Power Forward",
    blurb: "Long, mobile forward who attacks off the catch and defends multiple spots.",
    nbaReference: "Pascal Siakam",
    collegeReference: "Pascal Siakam (New Mexico State)",
    buildRange: "6'8\"–6'10\", long, mobile",
    dna: vec({
      height_percentile: 78, wingspan_ratio: 86, standing_reach: 80, vertical_explosiveness: 74,
      lateral_quickness: 72, first_step_burst: 74, strength_mass: 68, endurance: 86,
      catch_and_shoot: 66, off_dribble_shooting: 66, movement_shooting: 54, rim_finishing: 84,
      floater_short_mid: 70, post_scoring: 68, handle_under_pressure: 68, passing_vision: 70,
      off_screen_navigation: 56, off_ball_iq: 72, poa_containment: 74, lateral_slides: 74,
      def_screen_navigation: 72, rim_protection: 58, help_rotations: 76, rebounding: 72, steal_deflection: 68,
      pace_preference: 66, shot_location: 48, on_off_ball: 56, iso_vs_system: 56, physicality_tolerance: 72,
    }),
    definingSkills: ["rim_finishing", "first_step_burst", "post_scoring", "poa_containment", "handle_under_pressure"],
    commonWeaknesses: ["catch_and_shoot", "movement_shooting", "off_dribble_shooting", "rim_protection", "off_ball_iq"],
    trainingEmphasis: emph({ shooting: 0.8, finishing: 0.7, ballhandling: 0.65, perimeterDefense: 0.65, power: 0.6, speedAgility: 0.6 }),
  },

  // ==================== DEVELOPMENTAL / HONEST MOLDS ====================
  {
    id: "dev-undersized-rim-attacker",
    name: "Undersized Rim Attacker (needs a pull-up)",
    blurb: "Fearless downhill guard who must add a reliable pull-up to survive at D1.",
    nbaReference: "José Alvarado",
    collegeReference: "José Alvarado (Georgia Tech)",
    buildRange: "5'10\"–6'1\", quick, must add shooting range",
    developmental: true,
    dna: vec({
      height_percentile: 22, wingspan_ratio: 56, standing_reach: 26, vertical_explosiveness: 66,
      lateral_quickness: 86, first_step_burst: 82, strength_mass: 52, endurance: 88,
      catch_and_shoot: 58, off_dribble_shooting: 46, movement_shooting: 44, rim_finishing: 74,
      floater_short_mid: 70, post_scoring: 18, handle_under_pressure: 82, passing_vision: 74,
      off_screen_navigation: 58, off_ball_iq: 66, poa_containment: 88, lateral_slides: 88,
      def_screen_navigation: 66, rim_protection: 12, help_rotations: 64, rebounding: 34, steal_deflection: 92,
      pace_preference: 78, shot_location: 45, on_off_ball: 70, iso_vs_system: 50, physicality_tolerance: 72,
    }),
    definingSkills: ["first_step_burst", "poa_containment", "steal_deflection", "handle_under_pressure", "lateral_quickness"],
    commonWeaknesses: ["off_dribble_shooting", "movement_shooting", "height_percentile", "standing_reach", "rim_protection"],
    trainingEmphasis: emph({ shooting: 0.95, ballhandling: 0.75, perimeterDefense: 0.7, conditioning: 0.65, finishing: 0.55, strength: 0.55 }),
  },
  {
    id: "dev-tweener-needs-corner-three",
    name: "Athletic Tweener Forward (needs a corner three)",
    blurb: "Great athlete stuck between positions who needs a reliable corner three to fit a role.",
    nbaReference: "Aaron Gordon",
    collegeReference: "Aaron Gordon (Arizona)",
    buildRange: "6'6\"–6'8\", explosive, jumper unreliable",
    developmental: true,
    dna: vec({
      height_percentile: 64, wingspan_ratio: 82, standing_reach: 70, vertical_explosiveness: 92,
      lateral_quickness: 76, first_step_burst: 80, strength_mass: 78, endurance: 84,
      catch_and_shoot: 50, off_dribble_shooting: 44, movement_shooting: 40, rim_finishing: 88,
      floater_short_mid: 54, post_scoring: 52, handle_under_pressure: 58, passing_vision: 66,
      off_screen_navigation: 50, off_ball_iq: 70, poa_containment: 80, lateral_slides: 80,
      def_screen_navigation: 72, rim_protection: 60, help_rotations: 80, rebounding: 76, steal_deflection: 70,
      pace_preference: 66, shot_location: 42, on_off_ball: 46, iso_vs_system: 44, physicality_tolerance: 80,
    }),
    definingSkills: ["vertical_explosiveness", "rim_finishing", "poa_containment", "rebounding", "help_rotations"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "movement_shooting", "floater_short_mid", "handle_under_pressure"],
    trainingEmphasis: emph({ shooting: 0.95, finishing: 0.6, perimeterDefense: 0.7, power: 0.6, ballhandling: 0.55, playmaking: 0.5 }),
  },
  {
    id: "dev-non-shooting-lead-guard",
    name: "Non-Shooting Lead Guard (needs a jumper)",
    blurb: "Downhill passer whose defenders sag off — the jumper is the whole ceiling.",
    nbaReference: "Elfrid Payton",
    collegeReference: "Elfrid Payton (Louisiana)",
    buildRange: "6'2\"–6'4\", long, must add shooting",
    developmental: true,
    dna: vec({
      height_percentile: 52, wingspan_ratio: 78, standing_reach: 56, vertical_explosiveness: 64,
      lateral_quickness: 78, first_step_burst: 78, strength_mass: 58, endurance: 84,
      catch_and_shoot: 38, off_dribble_shooting: 34, movement_shooting: 30, rim_finishing: 76,
      floater_short_mid: 60, post_scoring: 34, handle_under_pressure: 82, passing_vision: 88,
      off_screen_navigation: 46, off_ball_iq: 64, poa_containment: 80, lateral_slides: 82,
      def_screen_navigation: 66, rim_protection: 24, help_rotations: 68, rebounding: 56, steal_deflection: 82,
      pace_preference: 76, shot_location: 30, on_off_ball: 78, iso_vs_system: 44, physicality_tolerance: 66,
    }),
    definingSkills: ["passing_vision", "handle_under_pressure", "poa_containment", "first_step_burst", "steal_deflection"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "movement_shooting", "floater_short_mid", "post_scoring"],
    trainingEmphasis: emph({ shooting: 0.95, playmaking: 0.7, perimeterDefense: 0.65, ballhandling: 0.6, finishing: 0.55, conditioning: 0.5 }),
  },
  {
    id: "dev-energy-guard-needs-handle",
    name: "Energy Defender (needs a tighter handle)",
    blurb: "Elite point-of-attack defender who must tighten the handle to stay on the floor offensively.",
    nbaReference: "Gary Payton II",
    collegeReference: "Gary Payton II (Oregon State)",
    buildRange: "6'2\"–6'4\", strong, disruptive",
    developmental: true,
    dna: vec({
      height_percentile: 50, wingspan_ratio: 82, standing_reach: 58, vertical_explosiveness: 84,
      lateral_quickness: 90, first_step_burst: 74, strength_mass: 74, endurance: 88,
      catch_and_shoot: 54, off_dribble_shooting: 40, movement_shooting: 40, rim_finishing: 80,
      floater_short_mid: 48, post_scoring: 30, handle_under_pressure: 44, passing_vision: 58,
      off_screen_navigation: 52, off_ball_iq: 72, poa_containment: 94, lateral_slides: 94,
      def_screen_navigation: 82, rim_protection: 40, help_rotations: 84, rebounding: 66, steal_deflection: 94,
      pace_preference: 68, shot_location: 40, on_off_ball: 40, iso_vs_system: 32, physicality_tolerance: 84,
    }),
    definingSkills: ["poa_containment", "lateral_slides", "steal_deflection", "help_rotations", "vertical_explosiveness"],
    commonWeaknesses: ["handle_under_pressure", "off_dribble_shooting", "catch_and_shoot", "passing_vision", "floater_short_mid"],
    trainingEmphasis: emph({ ballhandling: 0.9, shooting: 0.8, perimeterDefense: 0.7, playmaking: 0.6, conditioning: 0.55, finishing: 0.5 }),
  },
  {
    id: "dev-skilled-big-needs-strength",
    name: "Skilled Big (needs strength)",
    blurb: "Mobile, skilled big who gets moved off his spot — strength is the gate.",
    nbaReference: "Chet Holmgren",
    collegeReference: "Chet Holmgren (Gonzaga)",
    buildRange: "6'11\"+, skilled, needs to add mass",
    developmental: true,
    dna: vec({
      height_percentile: 92, wingspan_ratio: 92, standing_reach: 92, vertical_explosiveness: 70,
      lateral_quickness: 62, first_step_burst: 56, strength_mass: 42, endurance: 74,
      catch_and_shoot: 78, off_dribble_shooting: 58, movement_shooting: 56, rim_finishing: 78,
      floater_short_mid: 66, post_scoring: 56, handle_under_pressure: 56, passing_vision: 66,
      off_screen_navigation: 48, off_ball_iq: 74, poa_containment: 58, lateral_slides: 56,
      def_screen_navigation: 62, rim_protection: 90, help_rotations: 78, rebounding: 70, steal_deflection: 64,
      pace_preference: 55, shot_location: 55, on_off_ball: 42, iso_vs_system: 42, physicality_tolerance: 48,
    }),
    definingSkills: ["rim_protection", "catch_and_shoot", "standing_reach", "help_rotations", "off_ball_iq"],
    commonWeaknesses: ["strength_mass", "physicality_tolerance", "post_scoring", "rebounding", "first_step_burst"],
    trainingEmphasis: emph({ strength: 0.95, interiorDefense: 0.7, finishing: 0.6, shooting: 0.6, power: 0.6, conditioning: 0.55 }),
  },
  {
    id: "dev-shooting-specialist-needs-defense",
    name: "Shooting Specialist (needs to be playable on defense)",
    blurb: "Knockdown movement shooter who must become good enough defensively to stay on the floor.",
    nbaReference: "Duncan Robinson",
    collegeReference: "Duncan Robinson (Michigan)",
    buildRange: "6'6\"–6'8\", shooter, defensive question mark",
    developmental: true,
    dna: vec({
      height_percentile: 64, wingspan_ratio: 62, standing_reach: 64, vertical_explosiveness: 52,
      lateral_quickness: 52, first_step_burst: 50, strength_mass: 54, endurance: 90,
      catch_and_shoot: 96, off_dribble_shooting: 62, movement_shooting: 94, rim_finishing: 58,
      floater_short_mid: 52, post_scoring: 36, handle_under_pressure: 52, passing_vision: 56,
      off_screen_navigation: 94, off_ball_iq: 84, poa_containment: 44, lateral_slides: 44,
      def_screen_navigation: 52, rim_protection: 34, help_rotations: 54, rebounding: 48, steal_deflection: 48,
      pace_preference: 55, shot_location: 78, on_off_ball: 34, iso_vs_system: 30, physicality_tolerance: 50,
    }),
    definingSkills: ["catch_and_shoot", "movement_shooting", "off_screen_navigation", "off_ball_iq", "endurance"],
    commonWeaknesses: ["poa_containment", "lateral_slides", "def_screen_navigation", "handle_under_pressure", "first_step_burst"],
    trainingEmphasis: emph({ perimeterDefense: 0.95, speedAgility: 0.7, strength: 0.6, ballhandling: 0.55, conditioning: 0.6, shooting: 0.5 }),
  },
  {
    id: "dev-slasher-needs-shooting",
    name: "Athletic Slasher (needs a jump shot)",
    blurb: "Explosive rim attacker whose lack of a jumper lets defenders go under everything.",
    nbaReference: "Hamidou Diallo",
    collegeReference: "Hamidou Diallo (Kentucky)",
    buildRange: "6'4\"–6'6\", elite athlete, unreliable shot",
    developmental: true,
    dna: vec({
      height_percentile: 58, wingspan_ratio: 84, standing_reach: 62, vertical_explosiveness: 96,
      lateral_quickness: 80, first_step_burst: 92, strength_mass: 70, endurance: 84,
      catch_and_shoot: 44, off_dribble_shooting: 36, movement_shooting: 34, rim_finishing: 90,
      floater_short_mid: 46, post_scoring: 38, handle_under_pressure: 58, passing_vision: 54,
      off_screen_navigation: 48, off_ball_iq: 58, poa_containment: 76, lateral_slides: 78,
      def_screen_navigation: 64, rim_protection: 46, help_rotations: 62, rebounding: 62, steal_deflection: 78,
      pace_preference: 78, shot_location: 34, on_off_ball: 58, iso_vs_system: 52, physicality_tolerance: 74,
    }),
    definingSkills: ["vertical_explosiveness", "first_step_burst", "rim_finishing", "poa_containment", "steal_deflection"],
    commonWeaknesses: ["catch_and_shoot", "off_dribble_shooting", "movement_shooting", "floater_short_mid", "passing_vision"],
    trainingEmphasis: emph({ shooting: 0.95, ballhandling: 0.7, finishing: 0.55, perimeterDefense: 0.6, playmaking: 0.5, power: 0.55 }),
  },
];

export const ARCHETYPES_BY_ID: Record<string, Archetype> = Object.fromEntries(
  ARCHETYPES.map((a) => [a.id, a]),
);

if (ARCHETYPES.length < 30) {
  // Guardrail: the spec requires ≥30 archetypes. Fail loudly at import time if a
  // future edit drops below the floor.
  throw new Error(`Archetype library has ${ARCHETYPES.length} entries; spec requires ≥30.`);
}
