/**
 * Advanced gym drill library (spec Part B.3). All 17 mandated exercises with full
 * schema objects. `muscleContributions` match the spec exactly and each sums to
 * 1.0 (asserted in library.test.ts). `videoRefs` are intentionally empty — real
 * YouTube refs are resolved by the Part C pipeline (F6), never hardcoded.
 */

import type { Exercise } from "./exercise";

const NO_VIDEOS = [] as Exercise["videoRefs"];

export const STRENGTH_EXERCISES: Exercise[] = [
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrust",
    aliases: ["hip thrust", "loaded glute bridge (bench)"],
    pattern: "hinge",
    category: "max_strength",
    level: 3,
    equipment: ["barbell", "bench"],
    unilateral: false,
    muscleContributions: { glute_max: 0.55, hamstring: 0.2, quad: 0.1, erector_spinae: 0.1, adductor: 0.05 },
    fatigueMultiplier: 1.0,
    recoveryClass: "normal",
    setup: [
      "Shoulder blades on the bench pad at the bottom of the scapula.",
      "Feet flat, positioned so shins are VERTICAL at the top of the rep (not the bottom) — the #1 setup error.",
      "Barbell in a pad over the hip crease; chin tucked, ribs down.",
    ],
    execution: [
      "Drive through the heels and extend the hips to full lockout.",
      "2-second squeeze at the top with the pelvis posteriorly tilted.",
      "Lower under control to just above the floor.",
    ],
    cues: ["Ribs down, tuck the tailbone", "Push the floor away through your heels", "Squeeze, don't arch"],
    commonFaults: [
      { fault: "Hyperextending the lumbar spine instead of extending the hip", fix: "Posterior pelvic tilt cue — 'ribs down, tuck the tailbone'" },
      { fault: "Pushing through the toes", fix: "Rock weight to the heels; keep the whole foot planted" },
      { fault: "Bench too high", fix: "Bench pad at the bottom of the shoulder blade, not mid-back" },
    ],
    tempo: "21X2",
    breathing: "Inhale at the bottom, brace, exhale through the drive.",
    prescription: [{ goal: "strength", sets: [3, 4], reps: [6, 10], restSeconds: [120, 180], rirTarget: 1 }],
    loadGuidance: {
      method: "bodyweight_ratio",
      beginner: "Bodyweight → 0.4× BW on the bar",
      intermediate: "0.75–1.25× BW (90 kg athlete ≈ 70–110 kg)",
      advanced: "1.5–2.0× BW for 8 reps",
      notes: "Prefer % of estimated hip-thrust 1RM once you have ≥3 logged sets.",
    },
    progressions: ["b-stance-hip-thrust", "single-leg-hip-thrust"],
    regressions: ["barbell-glute-bridge-floor", "single-leg-glute-bridge"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "db-reverse-lunge",
    name: "Dumbbell Reverse Lunge",
    aliases: ["reverse lunge", "step-back lunge"],
    pattern: "lunge",
    category: "max_strength",
    level: 2,
    equipment: ["dumbbells"],
    unilateral: true,
    muscleContributions: { quad: 0.3, glute_max: 0.28, hamstring: 0.15, glute_med: 0.12, adductor: 0.1, erector_spinae: 0.05 },
    fatigueMultiplier: 1.1,
    recoveryClass: "normal",
    setup: ["DBs at sides, neutral grip.", "Tall posture, feet hip-width."],
    execution: [
      "Step back to a controlled knee-tap (do not slam the knee).",
      "Front shin near vertical; torso pitched ~10–15° forward to bias the glute.",
      "Drive through the front heel to return — the back leg is a kickstand, not an engine.",
    ],
    cues: ["Spread the floor with the front foot", "Soft knee-tap", "Front heel drives you up"],
    commonFaults: [
      { fault: "Front knee caving in", fix: "'Spread the floor' — track the knee over the mid-foot" },
      { fault: "Over-striding so the front heel lifts", fix: "Shorten the step; keep the heel planted" },
      { fault: "Torso collapsing forward under load", fix: "Lighter DBs; brace the trunk" },
    ],
    tempo: "3010",
    breathing: "Inhale on the step-back, exhale on the drive up.",
    prescription: [{ goal: "strength", sets: [3, 4], reps: [6, 8], restSeconds: [90, 120], rirTarget: 1 }],
    loadGuidance: {
      method: "bodyweight_ratio",
      beginner: "Bodyweight → 2 × 8 kg DBs",
      intermediate: "DBs totaling 30–50% BW (90 kg ≈ 2 × 15–22 kg)",
      advanced: "DBs 60–80% BW, or barbell 0.6–0.9× BW",
      notes: "Reverse over forward: far lower knee shear, self-limiting eccentric — the jumper's lunge.",
    },
    progressions: ["deficit-reverse-lunge", "reverse-lunge-knee-drive"],
    regressions: ["split-squat-bodyweight"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "quarter-squat-explosive-push",
    name: "Quarter-Squat Explosive Push (Speed Squat)",
    aliases: ["speed squat", "explosive quarter squat"],
    pattern: "squat",
    category: "speed_strength",
    level: 4,
    equipment: ["barbell", "rack"],
    unilateral: false,
    muscleContributions: { quad: 0.4, glute_max: 0.25, gastrocnemius: 0.13, erector_spinae: 0.1, hamstring: 0.07, soleus: 0.05 },
    fatigueMultiplier: 1.3,
    recoveryClass: "fast",
    setup: ["Bar in high-bar position, safeties set.", "Feet in normal squat stance."],
    execution: [
      "Dip to ~a quarter depth (25–35% of full range, thighs WELL above parallel), 1s controlled descent.",
      "Drive up as violently as possible — heels stay down, NO jump with a barbell on the back.",
      "Reset fully between reps. This is not a bouncing set.",
    ],
    cues: ["Launch the bar", "Stay grounded, heels down", "Full reset every rep"],
    commonFaults: [
      { fault: "Loading it up as an ego quarter-squat", fix: "Speed-strength means submaximal load + maximal intent — end the set when bar speed drops" },
      { fault: "Bouncing reps", fix: "Full pause and reset between each" },
    ],
    tempo: "10X0",
    breathing: "Big brace held across the rep; reset breath between reps.",
    prescription: [{ goal: "power", sets: [4, 6], reps: [3, 3], restSeconds: [150, 180], rirTarget: 4 }],
    loadGuidance: {
      method: "percent_1rm",
      beginner: "Use a regression instead (trap-bar jump / DB CMJ)",
      intermediate: "30–45% of full-depth back squat 1RM",
      advanced: "45–60% 1RM; with VBT target 0.9–1.1 m/s, end set on >10% velocity drop",
      intensityProxy: 0.45,
      notes: "SPEED-STRENGTH, not a heavy partial. Terminate the moment bar speed visibly drops.",
    },
    progressions: [],
    regressions: ["trap-bar-jump", "db-countermovement-jump"],
    contraindications: ["current knee pain", "same day as heavy depth-drop session", "low-readiness day"],
    videoRefs: NO_VIDEOS,
    youthRestricted: true,
  },
  {
    id: "band-resisted-push-up",
    name: "Band-Resisted Push-Up",
    aliases: ["banded push-up"],
    pattern: "horizontal_push",
    category: "hypertrophy",
    level: 2,
    equipment: ["bands"],
    unilateral: false,
    muscleContributions: { pec_major: 0.35, triceps: 0.28, anterior_deltoid: 0.2, serratus_core: 0.12, rectus_abdominis: 0.05 },
    fatigueMultiplier: 1.0,
    recoveryClass: "fast",
    setup: [
      "Loop band across the upper back, ends anchored under both palms.",
      "Hands just outside shoulder width; body in one line from ear to ankle.",
      "Elbows tracking ~45° from the torso.",
    ],
    execution: [
      "Lower until the chest is a fist's height from the floor.",
      "Press to full lockout and PROTRACT at the top (push the floor away — trains serratus and shoulder health).",
    ],
    cues: ["One line, ear to ankle", "Elbows 45°, not flared", "Push the floor away at the top"],
    commonFaults: [
      { fault: "Hips sagging", fix: "Squeeze glutes, brace — 'one line'" },
      { fault: "Elbows flaring to 90°", fix: "Tuck to ~45°" },
      { fault: "Band sliding to the neck", fix: "Reposition across the mid-upper back" },
    ],
    tempo: "20X1",
    breathing: "Inhale down, exhale on the press.",
    prescription: [{ goal: "hypertrophy", sets: [4, 4], reps: [6, 12], restSeconds: [90, 90], rirTarget: 1 }],
    loadGuidance: {
      method: "band",
      beginner: "No band, elevate hands",
      intermediate: "Light band (~7–14 kg at lockout)",
      advanced: "Medium band (~14–27 kg) or double-band",
      intensityProxy: 0.55,
      notes: "Band resistance is nonlinear — log band color/rating + anchor, not an estimated kg.",
    },
    progressions: ["band-resisted-explosive-push-up"],
    regressions: ["push-up", "incline-push-up"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "trap-bar-jump",
    name: "Trap-Bar Jump",
    aliases: ["hex bar jump", "loaded jump"],
    pattern: "plyo",
    category: "plyometric",
    level: 3,
    equipment: ["trap_bar"],
    unilateral: false,
    muscleContributions: { quad: 0.35, glute_max: 0.3, gastrocnemius: 0.13, hamstring: 0.12, erector_spinae: 0.1 },
    fatigueMultiplier: 1.4,
    recoveryClass: "normal",
    setup: ["Trap bar loaded light (20–30% BW), athletic stance inside the bar."],
    execution: ["Countermovement dip and jump for max height.", "Land softly and reset every rep — no touch-and-go."],
    cues: ["Jump through the floor", "Soft, quiet landings", "Reset every rep"],
    commonFaults: [{ fault: "Grinding heavy reps", fix: "Keep it light (20–30% BW) — velocity is the point" }],
    tempo: "X",
    breathing: "Brace, explode, reset breath between reps.",
    prescription: [{ goal: "power", sets: [5, 5], reps: [3, 3], restSeconds: [120, 180], rirTarget: 4 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Bodyweight jump, no load", intermediate: "20–30% BW", advanced: "20–30% BW, focus on velocity", intensityProxy: 0.5, notes: "Counts toward plyometric ground contacts." },
    progressions: ["single-response-depth-jump"],
    regressions: ["db-countermovement-jump"],
    contraindications: ["low-readiness day"],
    videoRefs: NO_VIDEOS,
    countsPlyoContacts: true,
  },
  {
    id: "rfe-split-squat",
    name: "Rear-Foot-Elevated Split Squat",
    aliases: ["Bulgarian split squat", "RFE split squat"],
    pattern: "lunge",
    category: "max_strength",
    level: 3,
    equipment: ["dumbbells", "bench"],
    unilateral: true,
    muscleContributions: { quad: 0.35, glute_max: 0.3, adductor: 0.12, hamstring: 0.1, glute_med: 0.08, erector_spinae: 0.05 },
    fatigueMultiplier: 1.2,
    recoveryClass: "normal",
    setup: ["Bench ~40 cm.", "Front foot far enough forward that the front shin stays near vertical.", "Rear foot laces down on the bench."],
    execution: ["Lower straight down until the back knee nears the floor.", "Drive through the front heel to stand."],
    cues: ["Down, not forward", "Front shin vertical", "Weight in the front heel"],
    commonFaults: [{ fault: "Front foot too close (knee shear)", fix: "Step the front foot further out" }],
    tempo: "3010",
    breathing: "Inhale down, exhale up.",
    prescription: [{ goal: "strength", sets: [3, 4], reps: [6, 8], restSeconds: [90, 120], rirTarget: 1 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Bodyweight", intermediate: "DBs 40–60% BW total", advanced: "DBs 70–100% BW total", notes: "Deep unilateral loading — expect real quad/glute fatigue." },
    progressions: ["deficit-rfe-split-squat"],
    regressions: ["split-squat-bodyweight"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    aliases: ["Nordic curl", "Russian leg curl"],
    pattern: "hinge",
    category: "eccentric",
    level: 4,
    equipment: ["partner"],
    unilateral: false,
    muscleContributions: { hamstring: 0.7, glute_max: 0.12, erector_spinae: 0.1, gastrocnemius: 0.08 },
    fatigueMultiplier: 1.8,
    recoveryClass: "slow",
    setup: ["Kneel tall on a pad, ankles anchored (partner or strap).", "Hands ready to catch."],
    execution: ["Lower as slowly as possible (3–5s), resisting the whole way.", "Catch with the hands, push back up to reduce load. Eccentric-only to start."],
    cues: ["Fight gravity the whole way", "Hips locked out", "Slow — own the descent"],
    commonFaults: [{ fault: "Breaking at the hips", fix: "Keep a straight line knee-to-shoulder" }],
    tempo: "5010",
    breathing: "Exhale slowly through the descent.",
    prescription: [{ goal: "strength", sets: [3, 3], reps: [4, 6], restSeconds: [120, 180], rirTarget: 1 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Band-assisted, partial range", intermediate: "Bodyweight eccentric-only", advanced: "Full eccentric + assisted concentric", intensityProxy: 0.85, notes: "Max 2×/week; NEVER within 48h of sprinting. Lights up the map for days — by design." },
    progressions: ["nordic-full-rep"],
    regressions: ["band-assisted-nordic", "razor-curl"],
    contraindications: ["acute hamstring strain", "within 48h of sprinting"],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "copenhagen-plank",
    name: "Copenhagen Plank",
    aliases: ["Copenhagen adduction"],
    pattern: "core",
    category: "isometric",
    level: 3,
    equipment: ["bench"],
    unilateral: true,
    muscleContributions: { adductor: 0.6, obliques: 0.2, glute_med: 0.12, rectus_abdominis: 0.08 },
    fatigueMultiplier: 1.3,
    recoveryClass: "slow",
    setup: ["Side plank with the top leg's foot/knee on a bench.", "Bottom leg hovering."],
    execution: ["Hold a straight line; the top leg drives down into the bench.", "Short-lever (knee on bench) → long-lever (foot on bench)."],
    cues: ["Straight line hip to shoulder", "Squeeze the groin", "Don't let the hip drop"],
    commonFaults: [{ fault: "Hip sagging", fix: "Regress to short-lever" }],
    tempo: "hold",
    breathing: "Steady breathing through the hold.",
    prescription: [{ goal: "prehab", sets: [3, 3], reps: [1, 1], restSeconds: [45, 60], rirTarget: 1 }],
    loadGuidance: { method: "isometric_time", beginner: "Short-lever 15–20s/side", intermediate: "Long-lever 20–30s/side", advanced: "Long-lever 30s+ or +load", intensityProxy: 0.6, notes: "Reps field encodes holds; use 20–30s per side." },
    progressions: ["copenhagen-long-lever"],
    regressions: ["copenhagen-short-lever", "side-plank"],
    contraindications: ["acute groin strain"],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "single-leg-rdl",
    name: "Single-Leg Romanian Deadlift",
    aliases: ["SL RDL", "single-leg deadlift"],
    pattern: "hinge",
    category: "max_strength",
    level: 3,
    equipment: ["dumbbells"],
    unilateral: true,
    muscleContributions: { hamstring: 0.4, glute_max: 0.28, erector_spinae: 0.15, glute_med: 0.12, adductor: 0.05 },
    fatigueMultiplier: 1.2,
    recoveryClass: "slow",
    setup: ["DB in the opposite hand to the working leg.", "Soft knee, hips square."],
    execution: ["Hinge — don't squat; reach the back leg straight behind.", "Feel the hamstring stretch, then drive the hips through."],
    cues: ["Hinge, don't squat", "Hips square to the floor", "Reach the heel to the wall behind you"],
    commonFaults: [{ fault: "Rotating the hip open", fix: "Keep the back-leg toes pointing down" }],
    tempo: "3010",
    breathing: "Inhale on the hinge, exhale on the drive.",
    prescription: [{ goal: "strength", sets: [3, 3], reps: [8, 8], restSeconds: [90, 120], rirTarget: 1 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Bodyweight, hand on support", intermediate: "DB 15–30% BW", advanced: "DB 30–45% BW", notes: "Balance-limited — load conservatively." },
    progressions: ["deficit-sl-rdl"],
    regressions: ["b-stance-rdl"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "skater-bound-stick",
    name: "Lateral (Skater) Bound + 3-Second Stick",
    aliases: ["skater jump", "lateral bound"],
    pattern: "plyo",
    category: "plyometric",
    level: 3,
    equipment: ["none"],
    unilateral: true,
    muscleContributions: { glute_med: 0.3, glute_max: 0.25, quad: 0.2, adductor: 0.13, gastrocnemius: 0.12 },
    fatigueMultiplier: 1.4,
    recoveryClass: "normal",
    setup: ["Athletic stance, weight on one leg."],
    execution: ["Bound laterally and land on the opposite leg.", "STICK the landing for 3 seconds — the stick is the drill; distance is secondary."],
    cues: ["Stick it — freeze for 3", "Land soft, absorb", "Knee over the toe, not caving in"],
    commonFaults: [{ fault: "Chasing distance, sloppy landings", fix: "Shorten the bound; own the stick" }],
    tempo: "X (stick 3s)",
    breathing: "Exhale on the bound.",
    prescription: [{ goal: "power", sets: [4, 4], reps: [4, 4], restSeconds: [60, 90], rirTarget: 3 }],
    loadGuidance: { method: "plyo_contacts", beginner: "Short bound, focus on stick", intermediate: "Moderate distance + clean stick", advanced: "Continuous or resisted", intensityProxy: 0.5, notes: "Counts as plyo contacts." },
    progressions: ["continuous-skater-bounds"],
    regressions: ["lateral-step-and-stick"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
    countsPlyoContacts: true,
  },
  {
    id: "depth-drop-rebound-jump",
    name: "Depth Drop → Rebound Jump",
    aliases: ["depth jump", "shock method jump"],
    pattern: "plyo",
    category: "plyometric",
    level: 5,
    equipment: ["box"],
    unilateral: false,
    muscleContributions: { quad: 0.35, gastrocnemius: 0.22, glute_max: 0.2, soleus: 0.13, hamstring: 0.1 },
    fatigueMultiplier: 1.6,
    recoveryClass: "slow",
    setup: ["Box 30–45 cm. Requires a ≥0.5× BW squat and clean landing mechanics."],
    execution: ["Step (don't jump) off the box.", "On landing, minimize ground-contact time and rebound up explosively."],
    cues: ["Off the box, don't jump off", "Minimize ground time", "Land and pop — stiff ankles"],
    commonFaults: [{ fault: "Long, soft ground contact", fix: "Lower the box; think 'hot floor'" }],
    tempo: "X (min contact)",
    breathing: "Exhale on the rebound.",
    prescription: [{ goal: "power", sets: [3, 5], reps: [3, 3], restSeconds: [120, 180], rirTarget: 4 }],
    loadGuidance: { method: "plyo_contacts", beginner: "Not appropriate — use box jumps", intermediate: "Not appropriate", advanced: "30–45 cm box, quality contacts only", intensityProxy: 0.7, notes: "HARD CAPS: ≤40 high-intensity ground contacts/session, ≤2 sessions/week, green readiness only. Enforced by the scheduler." },
    progressions: [],
    regressions: ["box-jump", "single-response-depth-jump"],
    contraindications: ["current knee pain", "current Achilles pain", "low-readiness day"],
    videoRefs: NO_VIDEOS,
    countsPlyoContacts: true,
    youthRestricted: true,
  },
  {
    id: "half-kneeling-pallof-press",
    name: "Half-Kneeling Pallof Press",
    aliases: ["Pallof press"],
    pattern: "rotation",
    category: "isometric",
    level: 2,
    equipment: ["bands"],
    unilateral: true,
    muscleContributions: { obliques: 0.45, rectus_abdominis: 0.25, glute_med: 0.15, erector_spinae: 0.15 },
    fatigueMultiplier: 0.8,
    recoveryClass: "fast",
    setup: ["Half-kneeling, band anchored at chest height to the side.", "Ribs down, glute of the down leg engaged."],
    execution: ["Press the band straight out and hold 2s at full extension — resist the rotation.", "Return under control."],
    cues: ["Don't let it twist you", "Ribs down", "Squeeze the down-side glute"],
    commonFaults: [{ fault: "Letting the torso rotate", fix: "Lighter band; slow the tempo" }],
    tempo: "1 2 1 (2s hold)",
    breathing: "Exhale on the press, breathe through the hold.",
    prescription: [{ goal: "prehab", sets: [3, 3], reps: [10, 10], restSeconds: [45, 60], rirTarget: 2 }],
    loadGuidance: { method: "band", beginner: "Light band", intermediate: "Medium band, 2s holds", advanced: "Heavier band or longer lever", intensityProxy: 0.4, notes: "Anti-rotation core — low fatigue cost." },
    progressions: ["standing-pallof-press"],
    regressions: ["tall-kneeling-pallof-press"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "med-ball-rotational-scoop-toss",
    name: "Med-Ball Rotational Scoop Toss",
    aliases: ["rotational scoop toss", "shot-put toss"],
    pattern: "rotation",
    category: "plyometric",
    level: 3,
    equipment: ["med_ball", "wall"],
    unilateral: true,
    muscleContributions: { obliques: 0.4, glute_max: 0.2, rectus_abdominis: 0.15, adductor: 0.13, erector_spinae: 0.12 },
    fatigueMultiplier: 1.2,
    recoveryClass: "normal",
    setup: ["Side-on to a wall, 3–6 kg ball at the back hip."],
    execution: ["Load the back hip, then explosively rotate and scoop-toss into the wall.", "Intent is maximal — catch and reset."],
    cues: ["Fire from the hips", "Whip through the torso", "Max intent every rep"],
    commonFaults: [{ fault: "All arms, no hips", fix: "Start the toss from the ground up" }],
    tempo: "X",
    breathing: "Sharp exhale on the toss.",
    prescription: [{ goal: "power", sets: [4, 4], reps: [4, 4], restSeconds: [60, 90], rirTarget: 4 }],
    loadGuidance: { method: "rpe", beginner: "3 kg ball", intermediate: "4–5 kg ball", advanced: "5–6 kg ball", intensityProxy: 0.55, notes: "Rotational power — max intent, not volume." },
    progressions: ["step-behind-scoop-toss"],
    regressions: ["half-kneeling-scoop-toss"],
    contraindications: ["acute low-back pain"],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "weighted-pull-up",
    name: "Weighted Pull-Up",
    aliases: ["loaded pull-up"],
    pattern: "vertical_pull",
    category: "max_strength",
    level: 3,
    equipment: ["rack"],
    unilateral: false,
    muscleContributions: { lat: 0.4, biceps: 0.2, mid_lower_trap: 0.15, posterior_deltoid: 0.1, forearm: 0.1, rectus_abdominis: 0.05 },
    fatigueMultiplier: 1.1,
    recoveryClass: "normal",
    setup: ["Full hang, belt or DB between the feet.", "Shoulders set down and back."],
    execution: ["Pull the chest to the bar; control the descent to a full hang."],
    cues: ["Chest to bar", "Pull the elbows to the hips", "Full hang at the bottom"],
    commonFaults: [{ fault: "Kipping / half reps", fix: "Own bodyweight × 8 clean reps before loading" }],
    tempo: "20X1",
    breathing: "Exhale on the pull.",
    prescription: [{ goal: "strength", sets: [4, 4], reps: [4, 6], restSeconds: [120, 180], rirTarget: 1 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Assisted / bodyweight", intermediate: "Bodyweight × 8+ then add load", advanced: "+25–35% BW", intensityProxy: 0.7, notes: "Earn the load with clean bodyweight reps first." },
    progressions: ["weighted-pull-up-heavy"],
    regressions: ["band-assisted-pull-up", "lat-pulldown"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
    youthRestricted: true,
  },
  {
    id: "landmine-push-press",
    name: "Landmine Push Press",
    aliases: ["landmine press"],
    pattern: "vertical_push",
    category: "max_strength",
    level: 2,
    equipment: ["barbell"],
    unilateral: true,
    muscleContributions: { anterior_deltoid: 0.3, triceps: 0.22, pec_major: 0.15, quad: 0.13, obliques: 0.1, mid_lower_trap: 0.1 },
    fatigueMultiplier: 1.0,
    recoveryClass: "fast",
    setup: ["One end of a barbell in a landmine; other end at the shoulder.", "Athletic stance, ribs down."],
    execution: ["Slight leg dip, then drive the bar up and away to lockout.", "Control back to the shoulder."],
    cues: ["Dip and drive", "Ribs down", "Punch to the ceiling line"],
    commonFaults: [{ fault: "Overarching the low back", fix: "Brace; keep ribs down" }],
    tempo: "20X0",
    breathing: "Exhale on the press.",
    prescription: [{ goal: "strength", sets: [4, 4], reps: [5, 5], restSeconds: [90, 120], rirTarget: 1 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Empty bar", intermediate: "Add plates to a strong 5-rep", advanced: "Heavy 5s per side", intensityProxy: 0.55, notes: "Shoulder-friendly vertical push for athletes with overhead mobility limits." },
    progressions: ["standing-db-push-press"],
    regressions: ["half-kneeling-landmine-press"],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "seated-soleus-tibialis-pair",
    name: "Seated Soleus Raise + Tibialis Raise (paired)",
    aliases: ["soleus raise", "tibialis raise", "ankle durability pair"],
    pattern: "isolation",
    category: "prehab",
    level: 1,
    equipment: ["dumbbells", "wall"],
    unilateral: false,
    muscleContributions: { soleus: 0.55, tibialis_anterior: 0.45 },
    fatigueMultiplier: 0.7,
    recoveryClass: "fast",
    setup: ["Seated with knees bent ~90° (isolates the soleus).", "Load on the knees for the raise; wall/edge for the tibialis raise."],
    execution: ["Soleus raise: drive through the ball of the foot, slow tempo.", "Tibialis raise: pull the toes up to the shin, slow lower."],
    cues: ["Slow and full range", "Knees bent for the soleus", "Toes to shin on the tib raise"],
    commonFaults: [{ fault: "Bouncing", fix: "Slow the tempo — durability, not ego" }],
    tempo: "3011",
    breathing: "Normal.",
    prescription: [{ goal: "prehab", sets: [3, 3], reps: [15, 20], restSeconds: [45, 60], rirTarget: 2 }],
    loadGuidance: { method: "bodyweight_ratio", beginner: "Bodyweight", intermediate: "Light DBs on the knees", advanced: "Heavier load, slow tempo", intensityProxy: 0.5, notes: "The soleus takes ~6–8× BW in sprinting and almost nobody trains it seated." },
    progressions: ["single-leg-soleus-raise"],
    regressions: [],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
  {
    id: "banded-lateral-walk",
    name: "Banded Lateral Walk",
    aliases: ["monster walk", "banded side walk"],
    pattern: "lateral",
    category: "prehab",
    level: 1,
    equipment: ["bands"],
    unilateral: false,
    muscleContributions: { glute_med: 0.65, glute_max: 0.2, tfl: 0.15 },
    fatigueMultiplier: 0.6,
    recoveryClass: "fast",
    setup: ["Band above the knees, athletic half-squat stance."],
    execution: ["Step sideways, keeping constant tension; don't let the knees cave.", "Hold the athletic stance the whole set."],
    cues: ["Stay low", "Push the knees out", "Small, controlled steps"],
    commonFaults: [{ fault: "Standing up between steps", fix: "Hold the half-squat throughout" }],
    tempo: "controlled",
    breathing: "Normal.",
    prescription: [{ goal: "prehab", sets: [3, 3], reps: [12, 12], restSeconds: [30, 45], rirTarget: 2 }],
    loadGuidance: { method: "band", beginner: "Light band", intermediate: "Medium band", advanced: "Heavy band", intensityProxy: 0.35, notes: "Glute-med activation / prehab — very low fatigue cost." },
    progressions: ["banded-lateral-walk-heavy"],
    regressions: [],
    contraindications: [],
    videoRefs: NO_VIDEOS,
  },
];

export const STRENGTH_EXERCISES_BY_ID: Record<string, Exercise> = Object.fromEntries(
  STRENGTH_EXERCISES.map((e) => [e.id, e]),
);
